<?php

return [
    'settings' => [
        'logo_image' => null,
        'meta_title' => 'Back2Value | Bateri gjermane. Garanci reale. Shërbim vendor.',
        'meta_description' => 'Back2Value furnizon dhe mirëmban bateri industriale RID-Batterie për flota, UPS, institucionet financiare dhe infrastrukturat kritike në Shqipëri.',
        'accent_color' => '#17b78b',
        'hero_badge' => 'IMPORTUES EKSKLUZIV · RID-BATTERIE GJERMANI',
        'hero_title' => 'Bateri gjermane.',
        'hero_highlight' => 'Garanci reale.',
        'hero_subtitle' => 'Shërbim vendor.',
        'hero_description' => 'Furnizojmë dhe mirëmbajmë bateri industriale RID-Batterie — të vetmet origjinale gjermane në Shqipëri. Për pirunë, sisteme UPS dhe flota automjetesh.',
        'hero_cta' => 'Kërko Ofertë në WhatsApp',
        'hero_products_cta' => 'Shiko Produktet',
        'hero_image' => 'images/hero-illustration.svg',
        'hero_image_alt' => 'Ilustrim i baterive industriale RID-Batterie',
        'hero_image_width' => 560,
        'hero_image_height' => 440,
        'whatsapp_message' => 'Po interesohem për një ofertë për bateri industriale.',
        'products_eyebrow' => 'LINJAT E PRODUKTEVE',
        'products_title' => 'RID-Batterie',
        'products_description' => 'Bateri origjinale gjermane me garanci fabrike. Çmimet me kërkesë — na kontaktoni për ofertë B2B të personalizuar.',
        'services_eyebrow' => 'ÇFARË OFROJMË',
        'services_title' => 'Shërbimet Teknike',
        'services_description' => 'Nuk shesim thjesht produkte — ofrojmë zgjidhje të plota për të zgjatur jetën e pajisjeve tuaja.',
        'contact_eyebrow' => 'KONTAKTO',
        'contact_title' => 'Kërko një Ofertë',
        'contact_description' => 'Për çmime me shumicë, kontrata UPS ose bashkëpunim si servis dhe shpërndarës — na kontaktoni direkt.',
        'footer_description' => 'Importues ekskluziv i baterive RID-Batterie në Shqipëri, me fokus tek flotat, UPS, infrastruktura kritike dhe shërbimet teknike profesionale.',
        'phone' => '+355 69 273 4476',
        'whatsapp' => '+355692734476',
        'email' => 'hallo@b2v.al',
        'address' => 'Rruga Nehemia, Buçimas, Pogradec',
        'hours' => 'E hënë – E premte, 08:00 – 17:00',
        'map_query' => 'Rruga Nehemia, Buçimas, Pogradec',
    ],
    'navigation' => [
        'header_items' => [
            ['label' => 'Bateritë', 'target' => 'products'],
            ['label' => 'Shërbimet', 'target' => 'services'],
            ['label' => 'Zgjidhjet', 'target' => 'solutions'],
            ['label' => 'Qëndrueshmëria', 'target' => 'sustainability'],
            ['label' => 'Burimet', 'target' => 'resources'],
            ['label' => 'Kontakt', 'target' => 'contact'],
        ],
        'header_cta_secondary' => 'Rezervo Diagnostikim',
        'header_cta_secondary_target' => 'diagnostics',
        'header_cta_primary' => 'Na Kontaktoni',
        'floating_whatsapp_label' => 'Na kontaktoni në WhatsApp',
        'brand_alt' => 'Back2Value logo',
        'breadcrumb_home' => 'Kryefaqja',
        'footer_items' => [
            ['label' => 'Bateritë', 'target' => 'products'],
            ['label' => 'Shërbimet', 'target' => 'services'],
            ['label' => 'Rigjenerim', 'target' => 'regeneration'],
            ['label' => 'Zgjidhjet', 'target' => 'solutions'],
            ['label' => 'Qëndrueshmëria', 'target' => 'sustainability'],
            ['label' => 'Burimet', 'target' => 'resources'],
            ['label' => 'Diagnostikim', 'target' => 'diagnostics'],
        ],
        'footer_whatsapp_label' => 'WhatsApp',
        'footer_copyright' => 'Back2Value shpk. Të gjitha të drejtat e rezervuara.',
        'footer_partner_line' => 'Partner zyrtar RID-Batterie në Shqipëri',
    ],
    'compliance_banner' => [
        'enabled' => true,
        'prefix' => 'Back2Value operates in line with',
        'first_label' => 'Albanian waste-management legislation',
        'first_url' => 'https://akm.gov.al/ova_doc/ligj-nr-10463-date-22-9-2011-per-menaxhimin-e-integruar-te-mbetjeve/',
        'middle' => 'and the',
        'second_label' => 'EU regulatory framework',
        'second_url' => 'https://eur-lex.europa.eu/eli/reg/2023/1542/oj/',
        'suffix' => 'for batteries, waste batteries, and circular economy principles.',
    ],
    'contact_cards' => [
        'whatsapp_label' => 'WhatsApp',
        'email_label' => 'Email',
        'phone_label' => 'Telefon',
        'map_label' => 'Hap në Maps',
    ],
    'products' => [
        [
            'key' => 'traction',
            'title' => 'Bateri Traksionare (PzS)',
            'status' => 'Stock',
            'description' => 'Seria RID PzS për pirunë elektrike dhe makineri magazinash. Cikle të rënda pune, jetëgjatësi e lartë dhe konsum optimal energjie.',
            'features' => [
                'Përmasa DIN / BS — për të gjitha markat e pirunëve',
                'Jetëgjatësi e lartë ciklesh',
                'Garanci 2 vjet direkt nga fabrika',
            ],
            'image' => 'images/battery-pzs.jpg',
            'image_alt' => 'Bateri traksionare RID me qeliza industriale dhe kapakë portokalli',
            'sort_order' => 1,
        ],
        [
            'key' => 'ups-industrial',
            'title' => 'Bateri UPS & Industriale (AGM / OPzV)',
            'status' => 'Pre-order',
            'description' => 'RID Xtreme AGM dhe OPzV — pa mirëmbajtje, për sisteme kritike energjie, banka, telekomunikacion dhe qendra të dhënash.',
            'features' => [
                'Valve-regulated, zero mirëmbajtje',
                'Deri 20 vjet jetëgjatësi (OPzV)',
                'I përshtatshëm për auditimet e Bankës së Shqipërisë',
            ],
            'image' => 'images/battery-ups.jpg',
            'image_alt' => 'Bateri të gjelbra RID për sisteme UPS dhe përdorim industrial',
            'sort_order' => 2,
        ],
        [
            'key' => 'starting',
            'title' => 'Bateri Startimi (Flota & Kamionë)',
            'status' => 'Stock',
            'description' => 'Seria RID ST2 për kamionë, autobusë, makineri ndërtimi dhe flota tregtare. Fuqi e lartë startimi (CCA), edhe në temperatura ekstreme.',
            'features' => [
                'CCA e lartë — startim i besueshëm',
                'Shkëmbim me bateri të vjetër (core exchange)',
                'Garanci 2 vjet',
            ],
            'image' => 'images/battery-start.jpg',
            'image_alt' => 'Bateri startimi RID-Batterie për automjete dhe kamionë',
            'sort_order' => 3,
        ],
    ],
    'services' => [
        [
            'key' => 'diagnostics',
            'title' => 'Diagnostikim Profesional',
            'description' => 'Testim i gjendjes reale të kapacitetit (State of Health) me pajisje RID-Logger. Zbuloni gjendjen e baterisë para se të ndodhë një defekt.',
            'icon' => 'clipboard',
            'sort_order' => 1,
        ],
        [
            'key' => 'reconditioning',
            'title' => 'Rigjenerim & Rikthim Kapaciteti',
            'description' => 'Me anë të RID Tester kontrollohet, testohet dhe diagnostikohet bateria, rigjenerohet (shërbimi: rigjenerim bateria). Ky shërbim ofrohet falas brenda 3 vjetësh për çdo bateri të re të blerë tek Back2Value shpk, me anë të një database blerësit kontaktohen pas 1 viti pas blerjes për të kontrolluar gjendjen e baterisë dhe ofrohet rikarikimi nëse blerësi/subjekti dëshiron të optimizojë jetën e baterisë.',
            'icon' => 'refresh',
            'sort_order' => 2,
        ],
        [
            'key' => 'maintenance',
            'title' => 'Kontrata Mirëmbajtjeje (SLA)',
            'description' => 'Inspektime periodike, raporte teknike zyrtare për auditim dhe reagim emergjent brenda 48 orëve. Dokumentacion i plotë rregullator.',
            'icon' => 'calendar',
            'sort_order' => 3,
        ],
        [
            'key' => 'delivery',
            'title' => 'Grumbullim & Dorëzim',
            'description' => 'Marrim dhe kthejmë bateritë në të gjithë Shqipërinë. Shërbim i plotë logjistik që kursen kohë dhe ndërprerje në operacionet tuaja.',
            'icon' => 'download',
            'sort_order' => 4,
        ],
    ],
    'about' => [
        'eyebrow' => 'AVANTAZHI YNË',
        'title' => 'Pse Back2Value?',
        'description' => 'Jemi të vetmit që kombinojmë bateri gjermane origjinale me ekspertizë teknike vendore — në Shqipëri.',
        'points' => [
            [
                'key' => 'exclusive-importer',
                'title' => 'Importues Ekskluziv Gjerman',
                'icon' => 'shield',
                'description' => 'Back2Value shpk është partneri i vetëm i autorizuar i RID-Batterie Gjermani në Shqipëri. Çdo produkt ka garanci direkte nga fabrika — jo kopje, jo zëvendësues të tregut gri.',
                'label' => 'RID-Batterie GmbH, Gjermani',
            ],
            [
                'key' => 'local-service',
                'title' => 'Mirëmbajtje Profesionale Vendore',
                'icon' => 'refresh',
                'description' => 'Ofrojmë shërbimin teknik të vetëm të strukturuar për bateri industriale në Shqipëri. Diagnoza me RID-Logger, rigjenerim profesional dhe kontrata SLA me dokumentacion zyrtar — gjithçka nga baza jonë në Pogradec.',
                'label' => '',
            ],
        ],
    ],
    'stats' => [
        'items' => [
            ['key' => 'warranty', 'value' => '2yr', 'label' => 'Garanci Produkti', 'sort_order' => 1],
            ['key' => 'lifespan', 'value' => '20yr', 'label' => 'Jetëgjatësi OPzV', 'sort_order' => 2],
            ['key' => 'response', 'value' => '48h', 'label' => 'SLA Emergjent', 'sort_order' => 3],
            ['key' => 'rank', 'value' => '#1', 'label' => 'Importues Ekskluziv', 'sort_order' => 4],
        ],
    ],
    'trust' => [
        'items' => [
            ['key' => 'exclusive', 'text' => 'Importues Ekskluziv në Shqipëri', 'icon' => 'shield'],
            ['key' => 'german', 'text' => 'Prodhim Gjerman', 'icon' => 'factory'],
            ['key' => 'warranty', 'text' => 'Garanci 2 Vjet', 'icon' => 'calendar'],
            ['key' => 'service', 'text' => 'Shërbim Teknik · Pogradec', 'icon' => 'services'],
        ],
    ],
    'value_props' => [
        'eyebrow' => 'ZGJATIMI I JETËS SË BATERIVE',
        'title' => 'Rikthejmë 50–100% të kapacitetit origjinal',
        'description' => 'Diagnostikojmë, rikarikojmë dhe rigjenerojmë bateritë tuaja industriale para se ato të zëvendësohen. Rezultati: më shumë cikle jete, kosto operative më të ulëta dhe një ndikim mjedisor shumë më i vogël.',
        'items' => [
            [
                'key' => 'life-extension',
                'icon' => 'battery',
                'value' => '50–100%',
                'title' => 'Kapacitet i rikthyer',
                'description' => 'Me RID-Logger matim gjendjen reale (State of Health), pastaj me procesin e rigjenerimit rikthejmë 50–100% të kapacitetit origjinal dhe shtojmë cikle të reja pune.',
            ],
            [
                'key' => 'cost-reduction',
                'icon' => 'coins',
                'value' => '−60%',
                'title' => 'Ulje kostosh',
                'description' => 'Reaktivimi dhe mirëmbajtja periodike kushtojnë shumë më pak se blerja e baterive të reja, pa kompromentuar besueshmërinë e sistemeve kritike.',
            ],
            [
                'key' => 'responsible-management',
                'icon' => 'leaf',
                'value' => '100%',
                'title' => 'Menaxhim i përgjegjshëm',
                'description' => 'Grumbullojmë bateritë e përdorura, i dorëzojmë për riciklim të licencuar dhe dokumentojmë çdo hap të procesit sipas kërkesave mjedisore.',
            ],
        ],
    ],
    'diagnostics_teaser' => [
        'eyebrow' => 'DIAGNOSTIKIM I SHPEJTË',
        'title' => 'Rezervoni testimin e baterive tuaja',
        'description' => 'Dërgoni një kërkesë të shpejtë dhe ekipi teknik cakton testin, rigjenerimin ose grumbullimin e baterive brenda 24 orëve.',
        'steps' => [
            [
                'key' => 'request',
                'title' => 'Kërkesa',
                'description' => 'Plotësoni formularin online ose na shkruani në WhatsApp me numrin, llojin dhe vendndodhjen e baterive.',
            ],
            [
                'key' => 'assessment',
                'title' => 'Vlerësimi',
                'description' => 'Testojmë kapacitetin dhe rezistencën e brendshme me pajisje RID-Logger dhe përcaktojmë nëse bateria mund të rigjenerohet.',
            ],
            [
                'key' => 'reactivation',
                'title' => 'Rikthimi i kapacitetit',
                'description' => 'Aplikojmë procesin e rigjenerimit dhe rikarikimit, testojmë përsëri dhe ju dorëzojmë raportin zyrtar teknik.',
            ],
        ],
        'cta' => 'Rezervo Diagnostikim',
        'cta_target' => 'diagnostics',
        'secondary_cta' => 'Shiko shërbimet',
        'secondary_cta_target' => 'services',
    ],
    'circular_process' => [
        'eyebrow' => 'PROCESI YNË',
        'title' => 'Nga mbledhja te rikthimi në qarkullim',
        'description' => 'Çdo bateri kalon nëpër të njëjtin cikël të kontrolluar: grumbullim, testim, sortim dhe aktivizim — deri te rishitja ose riciklimi.',
        'steps' => [
            [
                'key' => 'collection',
                'icon' => 'truck',
                'title' => 'Mbledhja',
                'description' => 'Grumbullojmë bateritë e përdorura nga biznese, auto servise dhe individë në të gjithë Shqipërinë.',
            ],
            [
                'key' => 'testing',
                'icon' => 'pulse',
                'title' => 'Testimi',
                'description' => 'Çdo bateri testohet me RID Tester: matet kapaciteti real, rezistenca e brendshme dhe gjendja e rikarikimit.',
            ],
            [
                'key' => 'sorting',
                'icon' => 'layers',
                'title' => 'Sortimi',
                'description' => 'Bateritë ndahen sipas gjendjes: të rikthyeshme në punë, për përdorim të dytë ose për riciklim.',
            ],
            [
                'key' => 'activation',
                'icon' => 'zap',
                'title' => 'Aktivizimi',
                'description' => 'Bateritë e përshtatshme rigjenerohen me RID Rigenerator dhe rikthehen në qarkullim me performancë të verifikuar.',
            ],
        ],
        'note_eyebrow' => 'EKONOMI RRETHORE',
        'note_title' => 'Zero mbetje në landfill',
        'note_description' => 'Çdo hap dokumentohet — nga grumbullimi deri te destinoja përfundimtare, në përputhje me legjislacionin shqiptar dhe evropian për bateritë.',
        'note_cta' => 'Mëso për qëndrueshmërinë',
        'note_cta_target' => 'sustainability',
        'outcomes' => [
            [
                'key' => 'resale',
                'icon' => 'coins',
                'title' => 'Rishitje',
                'description' => 'Bateritë e rigjeneruara rikthehen në treg me garanci dhe raport teknik.',
            ],
            [
                'key' => 'recycling',
                'icon' => 'recycle',
                'title' => 'Riciklim',
                'description' => 'Çfarë nuk rikthehet në punë dërgohet për riciklim të licencuar.',
            ],
        ],
    ],
    'partners' => [
        'eyebrow' => 'PARTNERË & CERTIFIKIME',
        'title' => 'Të mbështetur nga partnerë ndërkombëtarë',
        'description' => 'Bashkëpunojmë me prodhues gjermanë dhe programme evropiane që garantojnë standarde teknike, transparencë dhe përgjegjshmëri mjedisore.',
        'items' => [
            [
                'key' => 'rid-battery',
                'name' => 'RID Battery GmbH',
                'country' => 'Gjermani',
                'description' => 'Prodhuesi gjerman i baterive industriale RID-Batterie dhe partneri ynë i prodhimit.',
            ],
            [
                'key' => 'enterprise-europe-network',
                'name' => 'Enterprise Europe Network Albania',
                'country' => 'Shqipëri · BE',
                'description' => 'Rrjeti evropian i mbështetjes së biznesit për inovacion, partneritete dhe zgjerim tregu.',
            ],
            [
                'key' => 'nehemiah-gateway',
                'name' => 'Nehemiah Gateway Albania',
                'country' => 'Shqipëri',
                'description' => 'Organizatë partnere për zhvillim të qëndrueshëm, trajnime teknike dhe projekte sociale.',
            ],
        ],
    ],
    'application_filters' => [
        'industrial' => [
            'label' => 'Industriale & Pirunë',
            'categories' => [
                'RID Motive Power (Forklifts)',
                'Hoppecke Series FNC (NiCd)',
                'Hoppecke Series GroE',
                'Hoppecke Series OGi',
            ],
        ],
        'backup_power' => [
            'label' => 'Backup Power & UPS',
            'application_types' => ['backup_power'],
        ],
        'solar' => [
            'label' => 'Solar & Energji e Rinovueshme',
            'application_types' => ['solar'],
        ],
        'auto' => [
            'label' => 'Auto & Automjete',
            'categories' => ['RID ST Series (Commercial Vehicles)'],
        ],
    ],
    'services_page' => [
        'meta_title' => 'Shërbimet Teknike | Back2Value',
        'meta_description' => 'Diagnostikim, rigjenerim, kontrata mirëmbajtjeje SLA dhe grumbullim baterish industriale në Shqipëri. Rezervoni një diagnostikim ose kërkoni kontratë servisi.',
        'eyebrow' => 'SHËRBIMET TONA',
        'title' => 'Zgjidhje të plota për jetëgjatësinë e baterive',
        'description' => 'Nga diagnostikimi i parë deri në grumbullimin e baterive të përdorura — mbulojmë të gjithë ciklin e jetës së baterive tuaja industriale.',
        'hero_cta_primary' => 'Rezervo Diagnostikim',
        'hero_cta_secondary' => 'Kalkulator kursimi',
        'hero_cta_secondary_target' => 'calculator',
        'detail_link' => 'RID Tester & RID Rigenerator',
        'detail_link_target' => 'regeneration',
        'items' => [
            [
                'key' => 'diagnostics',
                'icon' => 'clipboard',
                'title' => 'Diagnostikim & Vlerësim i Baterive',
                'description' => 'Matim kapacitetin real, rezistencën e brendshme dhe tensionin me pajisje RID-Logger, pastaj hartojmë raport teknik zyrtar mbi gjendjen e baterive (State of Health).',
                'features' => [
                    'Testim i plotë i bankës së baterive, qelizë për qelizë',
                    'Raport teknik zyrtar për auditim dhe vendimmarrje',
                    'Vlerësim i kostos së rigjenerimit kundrejt zëvendësimit',
                    'Rekomandim i shkruar për ciklin e ardhshëm të mirëmbajtjes',
                ],
            ],
            [
                'key' => 'reactivation',
                'icon' => 'refresh',
                'title' => 'Karikim & Rigjenerim i Baterive',
                'description' => 'Aplikojmë karikim të kontrolluar dhe pulse desulfimi për të rikthyer kapacitetin e humbur. Ky shërbim ofrohet falas brenda 3 vjetësh për bateritë e reja të blera nga Back2Value shpk.',
                'features' => [
                    'Rikthim i 50–100% të kapacitetit origjinal',
                    'Pulse desulfimi dhe balancim i qelizave',
                    'Rikariko fillimisht falas brenda 3 vjetësh nga blerja',
                    'Testim final dhe raport i kapacitetit të rikthyer',
                ],
            ],
            [
                'key' => 'maintenance',
                'icon' => 'calendar',
                'title' => 'Kontrata Mirëmbajtjeje (SLA)',
                'description' => 'Inspektime periodike, raporte teknike për auditim dhe reagim emergjent brenda 48 orëve — me kalendar të planifikuar sipas kritikalitetit të sistemeve tuaja.',
                'features' => [
                    'Kalendar inspektimesh periodike sipas SLA',
                    'Raportim zyrtar për kërkesat e Bankës së Shqipërisë',
                    'Reagim emergjent brenda 48 orëve',
                    'Menaxhim i inventarit të baterive dhe historikut të testeve',
                ],
            ],
            [
                'key' => 'trade-in',
                'icon' => 'download',
                'title' => 'Grumbullim & Trade-In i Baterive',
                'description' => 'Grumbullojmë bateritë e përdorura në të gjithë Shqipërinë, i transportojmë për riciklim të licencuar dhe ofrojmë vlerë trade-in për bateritë e reja.',
                'features' => [
                    'Grumbullim dhe transport i baterive të përdorura',
                    'Riciklim i licencuar me dokumentacion të plotë',
                    'Vlerë trade-in e zbritshme nga blerja e baterive të reja',
                    'Shërbim i përshtatshëm për auto servise dhe flota',
                ],
            ],
        ],
        'maintenance_eyebrow' => 'KONTRAKTA MIRËMBAJTJEJE',
        'maintenance_title' => 'Kërkoni një kontratë SLA për flotën tuaj',
        'maintenance_description' => 'Plotësoni të dhënat e mëposhtme dhe ekipi i shitjeve përgatit propozimin teknik dhe komercial për institucionin tuaj.',
        'form_company_label' => 'Emri i kompanisë',
        'form_contact_label' => 'Personi i kontaktit',
        'form_email_label' => 'Email',
        'form_phone_label' => 'Telefon',
        'form_sector_label' => 'Sektori',
        'form_sectors' => [
            'telecom' => 'Telekomunikacion',
            'data_center' => 'Data Center',
            'banks' => 'Banka & Institucione Financiare',
        ],
        'form_fleet_label' => 'Numri i baterive në flotë',
        'form_fleet_default' => '50',
        'form_requirements_label' => 'Kërkesat teknike',
        'form_requirements_hint' => 'Përshkruani lokacionet, llojin e baterive dhe frekuencën e dëshiruar të inspektimeve.',
        'form_message_label' => 'Shënime shtesë (opsionale)',
        'form_submit' => 'Dërgo kërkesën',
        'form_hint' => 'Përgjigjemi brenda 24 orëve të punës.',
        'cta_title' => 'Nuk jeni të sigurt nëse bateritë tuaja mund të rigjenerohen?',
        'cta_description' => 'Dërgoni një kërkesë për diagnostikim dhe marrim vendimin teknik bazuar në matje reale të kapacitetit dhe rezistencës së brendshme.',
        'cta_primary' => 'Rezervo Diagnostikim',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'Shiko produktet',
        'cta_secondary_target' => 'products',
    ],
    'calculator' => [
        'eyebrow' => 'VLERËSIM I SHPEJTË',
        'title' => 'Sa vlen rigjenerimi për bankën tuaj të baterive?',
        'description' => 'Vendosni numrin dhe peshën mesatare të baterive për të vlerësuar materialin e rikuperuar dhe uljen e kostos ndaj zëvendësimit.',
        'count_label' => 'Numri i baterive',
        'weight_label' => 'Pesha mesatare e një baterie (kg)',
        'count_default' => 24,
        'weight_default' => 32,
        'capacity_value' => '50–100%',
        'capacity_label' => 'Kapacitet i rikthyer me rigjenerim',
        'cost_value' => '−55%',
        'cost_label' => 'Kosto ndaj zëvendësimit me bateri të re',
        'lead_label' => 'Plumb i rikuperuar për riciklim të licencuar',
        'lead_unit' => 'kg',
        'co2_label' => 'CO₂ e shmangur nga prodhimi i baterive të re',
        'co2_unit' => 'kg',
        'note' => 'Vlerësimi bazohet në përvojën tonë teknike: rikthim 50–100% i kapacitetit, ulje mesatare 55% e kostos ndaj zëvendësimit, përmbajtje plumbi rreth 55% e peshës dhe shmangie e rreth 1.6 kg CO₂ për kilogram plumbi të rikuperuar. Shifrat janë indikative — rezultati real përcaktohet pas diagnostikimit teknik.',
        'primary_label' => 'Rezervo Diagnostikim',
        'primary_target' => 'diagnostics',
        'secondary_label' => 'Shiko ndikimin mjedisor',
        'secondary_target' => 'sustainability',
        'lead_share_percent' => 55,
        'co2_per_kg' => 2,
    ],
    'regeneration_page' => [
        'meta_title' => 'RID Tester & RID Rigenerator | Back2Value',
        'meta_description' => 'Test, diagnostikim dhe rigjenerim profesional i baterive me pajisjet RID Tester dhe RID Rigenerator. Falas brenda 3 vjetësh për çdo bateri të re.',
        'eyebrow' => 'SHËRBIME TEKNIKE',
        'title' => 'RID Tester & RID Rigenerator',
        'description' => 'Test, diagnostikim dhe rigjenerim baterish si shërbim profesional për klientët e Back2Value — jo si produkte për shitje.',
        'hero_cta_primary' => 'Rezervo Diagnostikim',
        'hero_cta_secondary' => 'Shiko shërbimet',
        'hero_cta_secondary_target' => 'services',
        'teaser_eyebrow' => 'RIGJENERIM BATERIE',
        'teaser_title' => 'RID Tester & RID Rigenerator',
        'teaser_description' => 'Bazës së shërbimit tonë të rigjenerimit i qëndrojnë dy pajisje profesionale: RID Tester kontrollon, teston dhe diagnostikon çdo bateri, ndërsa RID Rigenerator rikthen kapacitetin e humbur. Të dyja ofrohen si shërbim për klientët, jo si produkte për shitje.',
        'teaser_cta' => 'Mëso më shumë',
        'teaser_cta_target' => 'regeneration',
        'teaser_secondary_cta' => 'Rezervo Diagnostikim',
        'teaser_secondary_cta_target' => 'diagnostics',
        'tools_eyebrow' => 'DY PAJISJET TONA',
        'tools_title' => 'Pajisjet që përdorim çdo ditë',
        'tools_description' => 'Të dyja pajisjet janë pjesë e bazës së shërbimit tonë teknik në Pogradec dhe përdoren për çdo bateri që na besohet.',
        'tools' => [
            [
                'key' => 'rid-tester',
                'icon' => 'battery',
                'model' => 'RID BMG-30 Battery Tester',
                'title' => 'RID Tester',
                'description' => 'Me anë të RID Tester kontrollohet, testohet dhe diagnostikohet bateria: matet kapaciteti reale, rezistenca e brendshme dhe gjendja e rikarikimit, për të kuptuar nëse bateria mund të rigjenerohet.',
                'features' => [
                    'Matje e kapacitetit dhe rezistencës së brendshme',
                    'Diagnostikim i gjendjes reale të baterisë (State of Health)',
                    'Vendos nëse bateria kualifikohet për rigjenerim',
                    'Raport teknik që rrugëton çdo vendimmarrje',
                ],
            ],
            [
                'key' => 'rid-rigenerator',
                'icon' => 'recycle',
                'model' => 'RID BRG Series Battery Regenerator',
                'title' => 'RID Rigenerator',
                'description' => 'RID Rigenerator aplikon procesin profesional të rigjenerimit me karikim të kontrolluar dhe pulse desulfimi, duke rikthyer deri në 50–100% të kapacitetit origjinal pa zëvendësuar bankën e baterive.',
                'features' => [
                    'Rikthim i 50–100% të kapacitetit origjinal',
                    'Karikim i kontrolluar dhe pulse desulfimi',
                    'Testim i dytë pas procesit me raport zyrtar',
                    'Ofrohet si shërbim — jo si produkt për shitje',
                ],
            ],
        ],
        'lab_eyebrow' => 'LABORATORI I BATERIVE',
        'lab_title' => 'Nga pranimi te testi i performancës',
        'lab_description' => 'Të njëjtin proces të dokumentuar e kalon çdo bateri që na besohet — pavarësisht nëse është një bateri e vetme apo një bankë e tërë baterish.',
        'lab_panel_title' => 'Si funksionon laboratori ynë i baterive:',
        'lab_brand_logo' => 'images/rid-lab/rid-wordmark.png',
        'lab_brand_alt' => 'RID Battery · Germany',
        'lab_steps' => [
            [
                'key' => 'pranimi',
                'title' => 'Pranimi',
                'description' => 'Na e sillni baterinë dhe mbështeteni te shërbimi ynë i plotë.',
                'image' => 'images/rid-lab/step-1.png',
                'alt' => 'Dorëzimi i baterisë në laboratorin e Back2Value',
                'width' => 440,
                'height' => 280,
            ],
            [
                'key' => 'diagnostikimi',
                'title' => 'Diagnostikimi i baterisë',
                'description' => 'Analizojmë gjendjen aktuale dhe vlerësojmë nëse rigjenerimi është i arsyeshëm teknikisht dhe ekonomikisht.',
                'image' => 'images/rid-lab/step-2.png',
                'alt' => 'Diagnostikimi i baterisë me RID Tester',
                'width' => 440,
                'height' => 334,
            ],
            [
                'key' => 'rigjenerimi',
                'title' => 'Rigjenerimi',
                'description' => 'Bateritë e përshtatshme trajtohen teknikisht në mënyrë të synuar dhe riaktivizohen.',
                'image' => 'images/rid-lab/step-3.png',
                'alt' => 'Rigjenerimi i baterisë me RID Rigenerator',
                'width' => 440,
                'height' => 365,
            ],
            [
                'key' => 'testi-performances',
                'title' => 'Testi i performancës',
                'description' => 'Testet përfundimtare konfirmojnë fuqinë, stabilitetin dhe gatishmërinë për përdorim.',
                'image' => 'images/rid-lab/step-4.png',
                'alt' => 'Testi final i performancës së baterisë së rigjeneruar',
                'width' => 440,
                'height' => 316,
            ],
        ],
        'lab_note' => 'Merrni një bateri të testuar dhe funksionale, së bashku me një vlerësim të detajuar: me të dhëna për jetëgjatësinë e mbetur të parashikuar dhe përqindjen e suksesit të rigjenerimit.',
        'lab_badge_image' => 'images/rid-lab/badge-quality.png',
        'lab_badge_alt' => 'Selli i cilësisë — bateri e kontrolluar nga Back2Value',
        'lab_badge_width' => 380,
        'lab_badge_height' => 343,
        'process_eyebrow' => 'SI FUNKSIONON',
        'process_title' => 'Nga blerja te rigjenerimi',
        'process_description' => 'Çdo bateri e re e blerë tek Back2Value shpk hyn në një cikël të dokumentuar kontrolli dhe rigjenerimi.',
        'process_steps' => [
            [
                'key' => 'purchase',
                'title' => 'Blerja dhe regjistrimi',
                'description' => 'Çdo bateri e re e blerë tek Back2Value shpk regjistrohet në database-in e blerësve.',
            ],
            [
                'key' => 'testing',
                'title' => 'Kontroll me RID Tester',
                'description' => 'Pas 1 viti nga blerja, ekipi ju kontakton për të kontrolluar gjendjen e baterisë dhe me RID Tester teston kapacitetin dhe rezistencën e saj.',
            ],
            [
                'key' => 'reconditioning',
                'title' => 'Rigjenerim me RID Rigenerator',
                'description' => 'Nëse bateria kualifikohet, ofrohet rikarikimi i kontrolluar dhe rigjenerimi për të optimizuar jetën e saj — me raport teknik zyrtar.',
            ],
        ],
        'offer_eyebrow' => 'OFERTA PËR KLIENTËT',
        'offer_title' => 'Falas brenda 3 vjetësh për çdo bateri të re',
        'offer_description' => 'Ky shërbim ofrohet falas brenda 3 vjetësh për çdo bateri të re të blerë tek Back2Value shpk. Me anë të një database, blerësit kontaktohen pas 1 viti nga blerja për të kontrolluar gjendjen e baterisë dhe u ofrohet rikarikimi nëse dëshironi të optimizoni jetën e saj.',
        'cta_title' => 'Dëshironi të shohni rigjenerimin në punë?',
        'cta_description' => 'Sillni baterinë në laboratorin tonë në Pogradec dhe ekipi teknik do ta diagnostikojë, rigjenerojë dhe t\'ju japë raportin zyrtar.',
        'cta_primary' => 'Rezervo Diagnostikim',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'Shiko shërbimet',
        'cta_secondary_target' => 'services',
    ],
    'solutions' => [
        'meta_title' => 'Zgjidhjet sipas sektorit | Back2Value',
        'meta_description' => 'Zgjidhje baterish për industri, energji të rinovueshme, automotive dhe sektorin publik: kontrata SLA, raportim teknik, rigjenerim dhe grumbullim në Shqipëri.',
        'eyebrow' => 'ZGJIDHJET SIPAS SEKTORIT',
        'title' => 'Për kë punojmë',
        'description' => 'Të njëjtat shërbime teknikë, të përshtatur sipas mënyrës se si operoni, buxhetit dhe kërkesave të dokumentacionit.',
        'hero_cta_primary' => 'Rezervo Diagnostikim',
        'hero_cta_secondary' => 'Shiko shërbimet',
        'hero_cta_secondary_target' => 'services',
        'items' => [
            [
                'key' => 'enterprise',
                'icon' => 'factory',
                'title' => 'Ndërmarrje & Industri',
                'audience' => 'Telekomunikacion, banka, data center, ndërtim, agrobiznes dhe logjistikë',
                'description' => 'Operacione me sisteme kritike që nuk tolerojnë ndërprerje. Projektet e mirëmbajtjes dhe reagimi i shpejtë parandalojnë dështimet e papritura të baterive.',
                'benefits' => [
                    'Kontrata SLA me reagim emergjent brenda 48 orëve',
                    'Raportim zyrtar për auditimet e Bankës së Shqipërisë',
                    'Menaxhim i plotë i inventarit të baterive sipas lokacionit',
                    'Zvogëlim i kostove operative të energjisë rezervë',
                ],
                'applications' => ['industrial', 'backup_power'],
            ],
            [
                'key' => 'renewable',
                'icon' => 'sun',
                'title' => 'Energji e Rinovueshme',
                'audience' => 'Operatorë sistemesh solare, projekte off-grid dhe përdorues të energjisë rezervë',
                'description' => 'Bateritë e sistemeve solare humbin kapacitet përpara se të jenë në fund të jetës. Testimi dhe rigjenerimi rikthejnë prodhimin e energjisë me një investim shumë më të vogël.',
                'benefits' => [
                    'Vlerësim i kapacitetit real të bankës së baterive',
                    'Balancim i qelizave dhe rikthim i kapacitetit të humbur',
                    'Këshillim teknik për dimensionimin e sistemit',
                    'Planifikim mirëmbajtjeje sipas stinëve',
                ],
                'applications' => ['solar'],
            ],
            [
                'key' => 'automotive',
                'icon' => 'car',
                'title' => 'Automotive & Konsumator',
                'audience' => 'Pronarë automjetesh, auto servise, familje dhe përdorues sistemesh diellore shtëpiake',
                'description' => 'Shërbim i shpejtë për bateritë e automjeteve dhe sistemeve shtëpiake, me grumbullim dhe vlerë trade-in për bateritë e përdorura.',
                'benefits' => [
                    'Testim i shpejtë dhe diagnozë e qartë',
                    'Vlerë trade-in për bateritë e vjetra',
                    'Rikariko dhe rigjenerim kur është teknikisht e mundur',
                    'Pika grumbullimi të aksesueshme në qytetet kryesore',
                ],
                'applications' => ['auto', 'solar'],
            ],
            [
                'key' => 'public-sector',
                'icon' => 'landmark',
                'title' => 'Sektor Publik',
                'audience' => 'Bashki, spitale, shkolla, institucione dhe ndërmarrje publike',
                'description' => 'Dokumentacion i plotë, procedura transparente prokurimi dhe mirëmbajtje e planifikuar për institucionet që administrojnë infrastrukturë kritike.',
                'benefits' => [
                    'Raporte teknike të përshtatshme për prokurim publik',
                    'Kalendar mirëmbajtjeje me afate të kontrolluara',
                    'Plan menaxhimi për bateritë në fund të jetës',
                    'Trajnim i stafit teknik për kontrollin bazë',
                ],
                'applications' => ['backup_power', 'industrial'],
            ],
        ],
        'process_eyebrow' => 'SI PUNOJMË',
        'process_title' => 'Nga vlerësimi teknik deri në raport',
        'process_description' => 'Çdo angazhim ndjek të njëjtat hapa: matje, vendim teknik i bazuar në të dhëna, ekzekutim dhe dokumentacion.',
        'process_steps' => [
            ['title' => 'Inventar & kritikalitet', 'description' => 'Regjistrojmë modelin, kapacitetin, datën e instalimit, lokacionin dhe kritikalitetin e çdo banke baterish.'],
            ['title' => 'Matje & vendim', 'description' => 'Testojmë kapacitetin dhe rezistencën e brendshme, pastaj krahasojmë rigjenerimin me zëvendësimin.'],
            ['title' => 'Ekzekutim & raport', 'description' => 'Aplikojmë shërbimin e zgjedhur, testojmë përsëri dhe dorëzojmë raportin zyrtar teknik për auditim.'],
        ],
        'cta_title' => 'Gjeni zgjidhjen për sektorin tuaj',
        'cta_description' => 'Nga flotat e pirunëve deri në bankat e baterive të data center-it — përshtatim shërbimin, kalendarin dhe dokumentacionin sipas kërkesave tuaja.',
        'cta_primary' => 'Rezervo Diagnostikim',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'Katalogu i produkteve',
        'cta_secondary_target' => 'products',
    ],
    'sustainability' => [
        'meta_title' => 'Qëndrueshmëria & përputhshmëria | Back2Value',
        'meta_description' => 'Zgjatja e jetës së baterive, riciklim i licencuar dhe dokumentacion për auditimet: si e menaxhojmë përgjegjshëm çdo bankë baterish në Shqipëri.',
        'eyebrow' => 'QËNDRUESHMËRIA & PËRPUTHSHMËRIA',
        'title' => 'Menaxhim i përgjegjshëm i baterive',
        'description' => 'Zgjatja e jetës së baterive është veprimi më i thjeshtë mjedisor: më pak plumb i nxjerrë, më pak bateri të hedhura dhe më pak energji e harxhuar për prodhim të re.',
        'hero_cta_primary' => 'Rezervo Diagnostikim',
        'hero_cta_secondary' => 'Shiko shërbimet',
        'hero_cta_secondary_target' => 'services',
        'commitments_eyebrow' => 'ANGAZHIMET TONA',
        'commitments_title' => 'Katër angazhime operative',
        'commitments_description' => 'Zbatojmë të njëjtat standarde për çdo klient — nga një bateri e vetme deri në flota të plota institucionale.',
        'commitments' => [
            [
                'key' => 'life-extension-first',
                'icon' => 'battery',
                'title' => 'Zgjatja e jetës para zëvendësimit',
                'description' => 'Gjithmonë vlerësojmë nëse një bateri mund të rigjenerohet përpara se t\'ju sugjerojmë blerjen e një baterie të re.',
            ],
            [
                'key' => 'licensed-recycling',
                'icon' => 'recycle',
                'title' => 'Riciklim i licencuar',
                'description' => 'Bateritë në fund të jetës grumbullohen dhe dorëzohen vetëm në impiante riciklimi të licencuara, me gjurmueshmëri të plotë.',
            ],
            [
                'key' => 'documentation',
                'icon' => 'document',
                'title' => 'Dokumentacion i plotë',
                'description' => 'Çdo grumbullim, test dhe trajtim dokumentohet, në mënyrë që subjekti të plotësojë kërkesat e auditeve mjedisore dhe financiare.',
            ],
            [
                'key' => 'customer-education',
                'icon' => 'academic',
                'title' => 'Edukim i klientëve',
                'description' => 'Trajnojmë stafin e klientëve për karikim, temperaturë pune, ventilim dhe mirëmbajtje bazë, për të zgjatur jetën e baterive.',
            ],
        ],
        'metrics' => [
            ['key' => 'capacity-restored', 'value' => '50–100%', 'label' => 'Kapacitet i rikthyer'],
            ['key' => 'cost-saved', 'value' => '−60%', 'label' => 'Kosto ndaj zëvendësimit'],
            ['key' => 'lead-recovered', 'value' => '98%', 'label' => 'Plumb i riciklueshëm'],
            ['key' => 'response', 'value' => '48h', 'label' => 'Reagim emergjent SLA'],
        ],
        'compliance_eyebrow' => 'DOKUMENTACION',
        'compliance_title' => 'Përputhshmëria & dokumentacioni',
        'compliance_description' => 'Mbështesim subjektet që duhet të provojnë mirëmbajtjen dhe trajtimin e baterive para audituesve dhe institucioneve mbikëqyrëse.',
        'compliance_points' => [
            'Raporte teknike për mirëmbajtjen e baterive të sistemeve UPS dhe energjisë rezervë',
            'Dokumentacion i mirëmbajtjes sipas kërkesave të mbikëqyrjes financiare (Vendimi Nr. 48/2024)',
            'Vërtetime grumbullimi dhe dorëzimi për riciklim të licencuar',
            'Regjistër i testeve, mirëmbajtjes dhe historikut të çdo banke baterish',
        ],
        'cta_title' => 'Ktheni bateritë në cikël pune, jo në mbetje',
        'cta_description' => 'Vlerësojmë kapacitetin real të baterive tuaja dhe ju tregojmë qartë kur rigjenerimi është zgjedhja e saktë.',
        'cta_primary' => 'Rezervo Diagnostikim',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'Qendra e burimeve',
        'cta_secondary_target' => 'resources',
    ],
    'resources' => [
        'meta_title' => 'Qendra e burimeve | Back2Value',
        'meta_description' => 'Udhëzues praktikë për jetëgjatësinë e baterive industriale: karikim, mirëmbajtje, kosto, riciklim dhe përgatitja e dokumentacionit për auditime.',
        'eyebrow' => 'EDUKIM I KLIENTËVE',
        'title' => 'Qendra e burimeve',
        'description' => 'Udhëzues praktikë mbi zgjatjen e jetës së baterive, përfitimet ekonomike dhe ato mjedisore.',
        'hero_cta_primary' => 'Rezervo Diagnostikim',
        'hero_cta_secondary' => 'Shërbimet teknike',
        'hero_cta_secondary_target' => 'services',
        'article_more_label' => 'Lexo udhëzuesin e plotë',
        'articles' => [
            [
                'key' => 'extend-battery-life',
                'category' => 'Jetëgjatësia e baterive',
                'title' => 'Si të zgjatni jetën e baterive tuaja industriale',
                'excerpt' => 'Temperatura, thellësia e shkarkimit dhe mirëmbajtja periodike përcaktojnë më shumë se çdo faktor tjetër sa do të zgjasë bateria.',
                'reading_time' => '4 min',
                'paragraphs' => [
                    'Temperatura e punës është faktori numër një: nga 25°C e lart, çdo rritje prej 10°C shkurton ndjeshëm jetën e pritshme të baterive me plumb-acid.',
                    'Thellësia e shkarkimit ndikon drejtpërdrejt në numrin e cikleve. Kufizimi i shkarkimit dhe kalimi në rikarikim në kohë rrisin ciklet totale që bateria mund të japë.',
                    'Kontrolli periodik i tensionit dhe rezistencës së brendshme zbulon qelizat e dobëta përpara se ato të dëmtojnë të gjithë bankën e baterive.',
                ],
            ],
            [
                'key' => 'reactivation-vs-replacement',
                'category' => 'Ekonomia',
                'title' => 'Rigjenerim apo zëvendësim? Si merr vendimin e saktë',
                'excerpt' => 'Jo çdo bateri duhet zëvendësuar. Kriteri është kapaciteti i mbetur dhe kushtet e përdorimit, jo mosha e baterisë.',
                'reading_time' => '5 min',
                'paragraphs' => [
                    'Kur kapaciteti i matur mbetet mbi gjysmën e kapacitetit të pritshëm, bateria zakonisht plotëson kushtet për rigjenerim dhe rikarikim të kontrolluar.',
                    'Vlerësimi duhet të përfshijë aksesin fizik, kushtet e ambientit dhe kritikalitetin e sistemit. Për banka baterish të vjetra dhe pa mbikëqyrje, zëvendësimi i planifikuar është më i sigurt.',
                    'Krahasimi i duhur nuk është vetëm kosto blerjeje: merrni parasysh konsumin e energjisë për rikarikim, humbjet e kapacitetit dhe kohën e ndërprerjes.',
                ],
            ],
            [
                'key' => 'environmental-impact',
                'category' => 'Qëndrueshmëria',
                'title' => 'Ndikimi mjedisor i baterive: çfarë ndryshon me rigjenerimin',
                'excerpt' => 'Riciklimi është i domosdoshëm, por zgjatja e jetës është hapi që parandalon krijimin e mbetjeve në burim.',
                'reading_time' => '4 min',
                'paragraphs' => [
                    'Prodhimi i një baterie të re kërkon nxjerrjen dhe përpunimin e plumbit, energji të konsiderueshme dhe transport ndërkombëtar. Zgjatja e jetës shmang këto kosto mjedisore për çdo vit shtesë shërbimi.',
                    'Rigjenerimi zvogëlon volumin e baterive që hyjnë në rrjedhën e mbetjeve dhe vonon blerjen e produkteve të reja.',
                    'Bateritë që dalin përfundimisht nga shërbimi dorëzohen për riciklim të licencuar, ku plumbi rikuperohet pothuajse plotësisht dhe rikthehet në prodhim.',
                ],
            ],
            [
                'key' => 'ups-battery-audit',
                'category' => 'Përputhshmëria',
                'title' => 'Kontrolli i baterive UPS për auditimet financiare',
                'excerpt' => 'Institucionet financiare duhet të dokumentojnë mirëmbajtjen e baterive të sistemeve UPS. Ja si përgatitet dosja.',
                'reading_time' => '6 min',
                'paragraphs' => [
                    'Audituesit kërkojnë provë që sistemet e energjisë rezervë mirëmbahen vazhdimisht dhe se bateritë zëvendësohen sipas planit.',
                    'Dosja duhet të përmbajë inventarin e baterive me datën e instalimit, raportet e testeve të kapacitetit, historikun e mirëmbajtjes dhe rekomandimet për zëvendësim.',
                    'Kontratat e mirëmbajtjes me raportim periodik i sigurojnë institucionit gjurmueshmërinë e plotë pa angazhimin e burimeve të brendshme.',
                ],
            ],
            [
                'key' => 'charging-best-practices',
                'category' => 'Operimi',
                'title' => 'Karikimi i saktë: gabimet që shkurtojnë jetën e baterive',
                'excerpt' => 'Karikim i tepërt, sulfatimi dhe qelizat e pabalancuara janë arsyet kryesore të humbjes së kapacitetit.',
                'reading_time' => '5 min',
                'paragraphs' => [
                    'Karikuesit me kompensim temperature dhe karikim në faza parandalojnë mbikarikimin, i cili shkakton humbje të elektrolitit dhe oksidim të pllakës pozitive.',
                    'Sulfatimi i plumbit është i kthyeshëm në faza të hershme: pulse desulfimi dhe cikle të kontrolluara rikarikimi rikthejnë pjesë të mirë të kapacitetit të humbur.',
                    'Qelizat e pabalancuara e shkarkojnë bankën në mënyrë të pabarabartë. Matja periodike dhe balancimi i qelizave ruajnë performancën e të gjithë sistemit.',
                ],
            ],
            [
                'key' => 'maintenance-plan',
                'category' => 'Mirëmbajtja',
                'title' => 'Si të ndërtohet një plan mirëmbajtjeje vjetore për bateritë',
                'excerpt' => 'Një kalendar i thjeshtë inspektimesh parandalon shpenzimet e papritura dhe ndërprerjet e sistemit.',
                'reading_time' => '5 min',
                'paragraphs' => [
                    'Filloni me një inventar të plotë: modeli, kapaciteti, data e instalimit, lokacioni dhe kritikaliteti i çdo banke baterish.',
                    'Përcaktoni frekuencën e inspektimeve sipas kritikalitetit: sistemet kritike kërkojnë kontroll tremujor, ato sekondare mjaftohen me kontroll vjetor.',
                    'Përfshini në plan testin e kapacitetit, matjen e rezistencës së brendshme, pastrimin e terminaleve dhe verifikimin e sistemit të karikimit.',
                ],
            ],
        ],
        'planning_eyebrow' => 'PLANIFIKIM',
        'planning_title' => 'Çfarë duhet të përgatitni para se të na kontaktoni',
        'planning_description' => 'Sa më i saktë inventari, aq më e shpejtë dhe më e saktë vlerësimi që ju kthejmë.',
        'planning_points' => [
            'Lista e baterive: marka, modeli, kapaciteti (Ah), voltazhi dhe data e blerjes',
            'Lokacioni i çdo banke baterish dhe aksesi për inspektim',
            'Fotografi të etiketave të baterive dhe të terminaleve',
            'Numri i baterive që keni zëvendësuar gjatë vitit të fundit',
        ],
        'cta_title' => 'Gati për të filluar?',
        'cta_description' => 'Dërgoni kërkesën tuaj të diagnostikimit dhe do të merrni një vlerësim teknik fillestar pa asnjë angazhim.',
        'cta_primary' => 'Rezervo Diagnostikim',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'Shiko shërbimet',
        'cta_secondary_target' => 'services',
    ],
    'drop_off_points' => [
        'eyebrow' => 'RRJETI I GRUMBULLIMIT',
        'title' => 'Pika grumbullimi dhe servisi të autorizuara',
        'description' => 'Pranojmë bateri për testim, rigjenerim dhe riciklim në pikat e mëposhtme. Për flota dhe banka të mëdha baterish organizojmë transport të dedikuar.',
        'items' => [
            [
                'key' => 'pogradec-hq',
                'title' => 'Pogradec — Qendra Kryesore Teknike',
                'type' => 'Laborator & servis i autorizuar',
                'category' => 'licensed',
                'address' => 'Rruga Nehemia, Buçimas, Pogradec',
                'phone' => '+355 69 273 4476',
                'hours' => 'E hënë – E premte · 08:00 – 17:00',
            ],
            [
                'key' => 'tirana-hub',
                'title' => 'Tiranë — Qendra e Servisit',
                'type' => 'Pikë grumbullimi e autorizuar',
                'category' => 'licensed',
                'address' => 'Tiranë (adresa konfirmohet pas kërkesës)',
                'phone' => '+355 69 273 4476',
                'hours' => 'E hënë – E shtunë · 08:30 – 18:00',
            ],
            [
                'key' => 'durres-point',
                'title' => 'Durrës — Pika e Grumbullimit',
                'type' => 'Qendër grumbullimi baterish',
                'category' => 'collection',
                'address' => 'Durrës (adresa konfirmohet pas kërkesës)',
                'phone' => '+355 69 273 4476',
                'hours' => 'E hënë – E premte · 09:00 – 17:30',
            ],
            [
                'key' => 'workshop-network',
                'title' => 'Rrjeti i Auto Serviseve Partnere',
                'type' => 'Servis partner automjetesh',
                'category' => 'workshop',
                'address' => 'Tiranë, Durrës, Fier, Shkodër, Elbasan',
                'phone' => '+355 69 273 4476',
                'hours' => 'Sipas orarit të servisit partner',
            ],
        ],
        'address_label' => 'Adresa',
        'phone_label' => 'Telefon',
        'hours_label' => 'Orari',
    ],
    'diagnostics_page' => [
        'meta_title' => 'Rezervo diagnostikim baterie | Back2Value',
        'meta_description' => 'Rezervo një diagnostikim profesional të baterive tuaja industriale: matje e kapacitetit, raport teknik zyrtar dhe vlerësim i rigjenerimit.',
        'eyebrow' => 'DIAGNOSTIKIM & RIGJENERIM',
        'title' => 'Rezervo një diagnostikim baterie',
        'description' => 'Plotësoni të dhënat e mëposhtme dhe ekipi teknik konfirmon termin, logjistikën dhe kushtet e shërbimit brenda 24 orëve.',
        'sectors' => [
            'enterprise' => 'Ndërmarrje & Industri',
            'telecom' => 'Telekomunikacion',
            'banking' => 'Banka & Data Center',
            'solar' => 'Solar & Energji e Rinovueshme',
            'auto' => 'Auto Servis & Flota',
            'household' => 'Familje & Konsumator',
            'public_sector' => 'Sektor Publik',
        ],
        'battery_types' => [
            'rid_industrial' => 'Bateri industriale RID-Batterie',
            'ups_backup' => 'Sistem UPS / energji rezervë',
            'solar_storage' => 'Bateri sistemi solar',
            'automotive' => 'Bateri automjeti / servisi',
            'forklift' => 'Bateri piruni / traksionare',
            'other' => 'Tjetër',
        ],
        'service_preferences' => [
            'pickup' => 'Grumbullim nga lokacioni ynë',
            'drop_off' => 'Dorëzim në pikën më të afërt',
            'onsite' => 'Testim në vend (on-site)',
            'courier' => 'Koordinim transporti me korrier',
        ],
        'label_name' => 'Emri dhe mbiemri',
        'label_company' => 'Kompania (opsionale)',
        'label_email' => 'Email',
        'label_phone' => 'Telefoni',
        'label_sector' => 'Sektori',
        'label_battery_type' => 'Lloji i baterive',
        'label_date' => 'Data e preferuar për testim',
        'label_service_preference' => 'Mënyra e preferuar e shërbimit',
        'label_notes' => 'Shënime shtesë (opsionale)',
        'placeholder_select' => 'Zgjidhni opsionin',
        'error_summary' => 'Formulari ka gabime që duhen korrigjuar:',
        'submit_label' => 'Dërgo kërkesën',
        'submit_hint' => 'Ju kontakt brenda 24 orëve pune.',
        'success_message' => 'Kërkesa u dërgua me sukses. Ekipi teknik do t\'ju kontaktojë brenda 24 orëve.',
        'cta_title' => 'Para se të dërgoni kërkesën',
        'cta_description' => 'Mbledhni sa më shumë të dhëna: modeli, kapaciteti dhe lokacioni e bëjnë vlerësimin tonin shumë më të saktë.',
        'cta_primary' => 'Shiko shërbimet',
        'cta_primary_target' => 'services',
        'cta_secondary' => 'Burimet edukative',
        'cta_secondary_target' => 'resources',
    ],
    'catalog_page' => [
        'meta_title' => 'Bateritë industriale gjermane | Back2Value',
        'meta_description' => 'Katalogu i baterive RID-Batterie: OPzS për pirunë, UPS dhe industri, bateri startimi dhe sisteme për energji të rinovueshme. Çmim me kërkesë, dorëzim në Shqipëri.',
        'badge' => 'Portofoli Zyrtar · RID Battery Gjermani',
        'hero_title' => 'Bateri industriale me kategori dhe përdorim të qartë',
        'hero_description' => 'Filtroni sipas aplikimit ose kërkoni sipas modelit. Çdo bateri vjen me garanci, dokumentim teknik dhe mundësinë e rigjenerimit pas ciklit të parë.',
        'price_note' => 'Çmimet shfaqen me kërkesë për porositë B2B — na kontaktoni për ofertë të personalizuar sipas sasisë dhe aplikimit.',
        'portfolio_label' => 'RID-Batterie GmbH · Bateri Gjermane',
        'whatsapp_message' => 'Po interesohem për bateri nga katalogu RID-Batterie.',
        'search_placeholder' => 'Kërko sipas modelit, markës ose kategorisë…',
        'search_button' => 'Kërko',
        'clear_button' => 'Pastro',
        'categories_label' => 'Kategoritë',
        'applications_label' => 'Aplikimi',
        'all_label' => 'Të gjitha',
        'model_unit_one' => 'model',
        'model_unit_many' => 'modele',
        'finder_title' => 'Gjeni baterinë sipas mjetit tuaj',
        'finder_description' => 'Zgjidhni tipin e mjetit dhe vitin, dhe ne do t\'ju tregojmë bateritë RID që përputhen me kërkesat e saj.',
        'finder_type_label' => 'Tipi i mjetit',
        'finder_type_placeholder' => 'Zgjidhni tipin',
        'finder_make_label' => 'Marka',
        'finder_make_placeholder' => 'Zgjidhni markën',
        'finder_model_label' => 'Modeli',
        'finder_model_placeholder' => 'Sprinter, Golf, A4…',
        'finder_year_label' => 'Viti',
        'finder_fuel_label' => 'Karburanti',
        'finder_startstop_label' => 'Start / Stop',
        'finder_capacity_label' => 'Kapaciteti (Ah)',
        'finder_capacity_placeholder' => '74',
        'finder_vin_label' => 'VIN (opsional)',
        'finder_vin_placeholder' => 'WVWZZZ1KZAW000001',
        'finder_notes_label' => 'Detaje të tjera (opsional)',
        'finder_notes_placeholder' => 'P.sh. kërkoj bateri AGM 100Ah për banak…',
        'finder_submit' => 'Gjej përshtatjen',
        'finder_reset' => 'Pastro',
        'finder_hint' => 'Rezultatet mbështeten në kategorinë e baterive startuese të flotës së RID. Për bateri industriale përdorni kërkesën e diagnostikimit.',
        'category_descriptions' => [
            'RID Motive Power' => 'Bateri traksionare për pirunë elektrike dhe makineri magazinash. Përmasa DIN/BS, cikle të rënda pune dhe garanci direkte nga fabrika.',
            'OPzS' => 'Banka baterive industriale për sisteme kritike: kapacitet i lartë, mirëmbajtje e reduktuar dhe jetëgjatësi deri në 20 vjet.',
            'OPzV' => 'Bateri AGM pa mirëmbajtje për UPS, telekomunikacion dhe data center. Zero mirëmbajtje dhe kapacitet i qëndrueshëm.',
            'FNC' => 'Seritë NiCd profesionale për lokomotiva, tramva dhe aplikacione industriale me cikle të thella.',
            'GroE' => 'Seritë me plumb për stacione benzine dhe rrjete elektrike: cikle të thella dhe besueshmëri në kushte ekstreme.',
            'OGi' => 'Bateri për makineri ndërtimi dhe pajisje të ngjashme, me kapacitet të lartë dhe rezistencë ndaj goditjeve mekanike.',
            'RID ST Series' => 'Bateri startimi për kamionë, autobusë dhe makineri ndërtimi me fuqi të lartë startimi dhe garanci 2 vjet.',
        ],
        'finder_year_placeholder' => 'Zgjidhni vitin',
        'finder_fuel_placeholder' => 'Zgjidhni karburantin',
        'vehicle_badge' => 'Kërkim mjeti',
        'vin_confirm_label' => 'Konfirmo përshtatjen me VIN',
        'category_fallback_description' => 'Zgjidhje profesionale për ruajtje dhe furnizim të pandërprerë energjie.',
        'empty_title' => 'Nuk u gjet asnjë bateri me këto kritere',
        'empty_description' => 'Provoni një kërkesë më të gjerë ose dërgoni kërkesë për një model specifik.',
        'empty_action' => 'Shfaq të gjitha bateritë',
        'quote_category' => 'Kërko ofertë për këtë kategori',
        'quote_whatsapp_message' => 'Po kërkoj ofertë për bateritë e kësaj kategorie.',
        'contact_title' => 'Kontakto me email ose telefon',
        'price_request_label' => 'Çmimi me kërkesë',
        'quote_button' => 'Kërko Ofertë',
        'warranty_prefix' => 'Garanci',
        'preorder_notice' => 'Të gjitha produket shiten me porosi paraprake. Na kontaktoni për kohën e dorëzimit dhe ofertën tuaj.',
        'stock_label_in_stock' => 'Në stok',
        'stock_label_low_stock' => 'Stok i kufizuar',
        'stock_label_on_preorder' => 'Porosi paraprake',
        'stock_label_out_of_stock' => 'Jashtë stokut',
        'vin_valid_text' => 'VIN-i u ndesh në katalogun tonë',
        'vin_region_label' => 'Rajoni',
        'vin_year_label' => 'Viti',
        'vin_match_text' => 'Rekomandojmë',
        'vin_invalid_text' => 'VIN-i nuk u ndesh. Na kontaktoni në WhatsApp për kontroll manual.',
        'recommendation_label' => 'modeli më i përshtatshëm',
        'bottom_kicker' => 'KONSULENCË TEKNIKE B2B',
        'bottom_title' => 'Ske i qartë cili model i përshtatet?',
        'bottom_description' => 'Na dërgoni listën e nevojave dhe do të marrni një propozim teknik me kapacitet, garanci dhe afat dorëzimi.',
        'bottom_primary' => 'Bisedo në WhatsApp',
        'bottom_secondary' => 'Shiko produktet',
    ],
];
