<?php

return [
    'settings' => [
        'meta_title' => 'Back2Value | Bateri gjermane. Garanci reale. Shërbim vendor.',
        'meta_description' => 'Back2Value furnizon dhe mirëmban bateri industriale RID-Batterie për flota, UPS, institucionet financiare dhe infrastrukturat kritike në Shqipëri.',
        'accent_color' => '#17b78b',
        'hero_badge' => 'IMPORTUES EKSKLUZIV · RID-BATTERIE GJERMANI',
        'hero_title' => 'Bateri gjermane.',
        'hero_highlight' => 'Garanci reale.',
        'hero_subtitle' => 'Shërbim vendor.',
        'hero_description' => 'Furnizojmë dhe mirëmbajmë bateri industriale RID-Batterie — të vetmet origjinale gjermane në Shqipëri. Për pirunë, sisteme UPS dhe flota automjetesh.',
        'hero_cta' => 'Kërko Ofertë në WhatsApp',
        'hero_products_cta' => 'Shiko Produktet',
        'promo_title' => 'Vendimi Nr. 48 (2024) i Bankës së Shqipërisë',
        'promo_description' => 'institucionet financiare duhet të dokumentojnë mirëmbajtjen e baterive UPS.',
        'promo_link' => 'Kontratat tona SLA ofrojnë dokumentacionin e plotë',
        'products_eyebrow' => 'LINJAT E PRODUKTEVE',
        'products_title' => 'RID-Batterie',
        'products_description' => 'Bateri origjinale gjermane me garanci fabrike. Çmimet me kërkesë — na kontaktoni për ofertë B2B të personalizuar.',
        'services_eyebrow' => 'ÇFARË OFROJMË',
        'services_title' => 'Shërbimet Teknike',
        'services_description' => 'Nuk shesim thjesht produkte — ofrojmë zgjidhje të plota për të zgjatur jetën e pajisjeve tuaja.',
        'contact_eyebrow' => 'KONTAKTO',
        'contact_title' => 'Kërko një Ofertë',
        'contact_description' => 'Për çmime me shumicë, kontrata UPS ose bashkëpunim si servis dhe shpërndarës — na kontaktoni direkt.',
        'footer_description' => 'Importues ekskluziv i baterive RID-Batterie në Shqipëri, me fokus tek flotat, UPS, infrastruktura kritike dhe shërbimet teknike profesionale.',
        'phone' => '+355 69 273 4476',
        'whatsapp' => '+355692734476',
        'email' => 'hallo@b2v.al',
        'address' => 'Rruga Nehemia, Buçimas, Pogradec',
        'hours' => 'E hënë – E premte, 08:00 – 17:00',
        'map_query' => 'Rruga Nehemia, Buçimas, Pogradec',
    ],
    'products' => [
        [
            'key' => 'traction',
            'title' => 'Bateri Traksionare (PzS)',
            'description' => 'Seria RID PzS për pirunë elektrike dhe makineri magazinash. Cikle të rënda pune, jetëgjatësi e lartë dhe konsum optimal energjie.',
            'features' => [
                'Përmasa DIN / BS — për të gjitha markat e pirunëve',
                'Jetëgjatësi e lartë ciklesh',
                'Garanci 2 vjet direkt nga fabrika',
            ],
            'image' => 'images/battery-pzs.jpg',
            'image_alt' => 'Bateri traksionare RID me qeliza industriale dhe kapakë portokalli',
            'sort_order' => 1,
        ],
        [
            'key' => 'ups-industrial',
            'title' => 'Bateri UPS & Industriale (AGM / OPzV)',
            'description' => 'RID Xtreme AGM dhe OPzV — pa mirëmbajtje, për sisteme kritike energjie, banka, telekomunikacion dhe qendra të dhënash.',
            'features' => [
                'Valve-regulated, zero mirëmbajtje',
                'Deri 20 vjet jetëgjatësi (OPzV)',
                'I përshtatshëm për auditimet e Bankës së Shqipërisë',
            ],
            'image' => 'images/battery-ups.jpg',
            'image_alt' => 'Bateri të gjelbra RID për sisteme UPS dhe përdorim industrial',
            'sort_order' => 2,
        ],
        [
            'key' => 'starting',
            'title' => 'Bateri Startimi (Flota & Kamionë)',
            'description' => 'Seria RID ST2 për kamionë, autobusë, makineri ndërtimi dhe flota tregtare. Fuqi e lartë startimi (CCA), edhe në temperatura ekstreme.',
            'features' => [
                'CCA e lartë — startim i besueshëm',
                'Shkëmbim me bateri të vjetër (core exchange)',
                'Garanci 2 vjet',
            ],
            'image' => 'images/battery-start.jpg',
            'image_alt' => 'Bateri startimi RID-Batterie për automjete dhe kamionë',
            'sort_order' => 3,
        ],
    ],
    'services' => [
        [
            'key' => 'diagnostics',
            'title' => 'Diagnostikim Profesional',
            'description' => 'Testim i gjendjes reale të kapacitetit (State of Health) me pajisje RID-Logger. Zbuloni gjendjen e baterisë para se të ndodhë një defekt.',
            'icon' => 'clipboard',
            'sort_order' => 1,
        ],
        [
            'key' => 'reconditioning',
            'title' => 'Rigjenerim & Rikthim Kapaciteti',
            'description' => 'Desulfatim profesional që rikthen kapacitetin e baterisë dhe zgjat jetëgjatësinë — duke shmangur zëvendësimin e panevojshëm.',
            'icon' => 'refresh',
            'sort_order' => 2,
        ],
        [
            'key' => 'maintenance',
            'title' => 'Kontrata Mirëmbajtjeje (SLA)',
            'description' => 'Inspektime periodike, raporte teknike zyrtare për auditim dhe reagim emergjent brenda 48 orëve. Dokumentacion i plotë rregullator.',
            'icon' => 'calendar',
            'sort_order' => 3,
        ],
        [
            'key' => 'delivery',
            'title' => 'Grumbullim & Dorëzim',
            'description' => 'Marrim dhe kthejmë bateritë në të gjithë Shqipërinë. Shërbim i plotë logjistik që kursen kohë dhe ndërprerje në operacionet tuaja.',
            'icon' => 'download',
            'sort_order' => 4,
        ],
    ],
    'about' => [
        'eyebrow' => 'AVANTAZHI YNË',
        'title' => 'Pse Back2Value?',
        'description' => 'Jemi të vetmit që kombinojmë bateri gjermane origjinale me ekspertizë teknike vendore — në Shqipëri.',
        'points' => [
            [
                'key' => 'exclusive-importer',
                'title' => 'Importues Ekskluziv Gjerman',
                'description' => 'Back2Value shpk është partneri i vetëm i autorizuar i RID-Batterie Gjermani në Shqipëri. Çdo produkt ka garanci direkte nga fabrika — jo kopje, jo zëvendësues të tregut gri.',
                'label' => 'RID-Batterie GmbH, Gjermani',
            ],
            [
                'key' => 'local-service',
                'title' => 'Mirëmbajtje Profesionale Vendore',
                'description' => 'Ofrojmë shërbimin teknik të vetëm të strukturuar për bateri industriale në Shqipëri. Diagnoza me RID-Logger, rigjenerim profesional dhe kontrata SLA me dokumentacion zyrtar — gjithçka nga baza jonë në Pogradec.',
                'label' => '',
            ],
        ],
    ],
    'stats' => [
        ['key' => 'warranty', 'value' => '2yr', 'label' => 'Garanci Produkti', 'sort_order' => 1],
        ['key' => 'lifespan', 'value' => '20yr', 'label' => 'Jetëgjatësi OPzV', 'sort_order' => 2],
        ['key' => 'response', 'value' => '48h', 'label' => 'SLA Emergjent', 'sort_order' => 3],
        ['key' => 'rank', 'value' => '#1', 'label' => 'Importues Ekskluziv', 'sort_order' => 4],
    ],
    'trust' => [
        'title' => 'Importues Ekskluziv në Shqipëri',
        'subtitle' => 'Prodhim Gjerman',
        'guarantee' => 'Garanci 2 Vjet',
        'service' => 'Shërbim Teknik · Pogradec',
    ],
];
