<?php

return [

    'settings' => [
        'logo_image' => null,
        'meta_title' => 'Back2Value | German batteries. Real warranty. Vendor service.',
        'meta_description' => 'Back2Value supplies and maintains RID-Batterie industrial batteries for fleets, UPS systems, financial institutions and critical infrastructure in Albania.',
        'accent_color' => '#17b78b',
        'hero_badge' => 'EXCLUSIVE IMPORTER · RID-BATTERIE GERMANY',
        'hero_title' => 'German batteries.',
        'hero_highlight' => 'Real warranty.',
        'hero_subtitle' => 'Vendor service.',
        'hero_description' => 'We supply and maintain RID-Batterie industrial batteries — the only genuine German originals in Albania. For forklifts, UPS systems and vehicle fleets.',
        'hero_cta' => 'Request a Quote on WhatsApp',
        'hero_products_cta' => 'View the Products',
        'hero_image' => 'images/hero-illustration.svg',
        'hero_image_alt' => 'Illustration of RID-Batterie industrial batteries',
        'hero_image_width' => 560,
        'hero_image_height' => 440,
        'whatsapp_message' => 'Hello! I am interested in a quote for industrial batteries.',
        'products_eyebrow' => 'PRODUCT LINES',
        'products_title' => 'RID-Batterie',
        'products_description' => 'Original German batteries with a factory warranty. Prices on request — contact us for a tailored B2B quote.',
        'services_eyebrow' => 'WHAT WE OFFER',
        'services_title' => 'Technical Services',
        'services_description' => 'We do not just move products — we deliver complete solutions that extend the life of your equipment.',
        'contact_eyebrow' => 'CONTACT',
        'contact_title' => 'Request a Quote',
        'contact_description' => 'For wholesale prices, UPS contracts or partnerships as a service and distributor — contact us directly.',
        'footer_description' => 'Exclusive importer of RID-Batterie batteries in Albania, with a focus on fleets, UPS, critical infrastructure and professional technical services.',
        'phone' => '+355 69 273 4476',
        'whatsapp' => '+355692734476',
        'email' => 'hallo@b2v.al',
        'address' => 'Rruga Nehemia, Buçimas, Pogradec',
        'hours' => 'Monday – Friday, 08:00 – 17:00',
        'map_query' => 'Rruga Nehemia, Buçimas, Pogradec',
    ],
    'navigation' => [
        'header_items' => [
            ['label' => 'Batteries', 'target' => 'products'],
            ['label' => 'Services', 'target' => 'services'],
            ['label' => 'Solutions', 'target' => 'solutions'],
            ['label' => 'Sustainability', 'target' => 'sustainability'],
            ['label' => 'About us', 'target' => 'resources'],
            ['label' => 'Contact', 'target' => 'contact'],
        ],
        'header_cta_secondary' => 'Book a Diagnostic',
        'header_cta_secondary_target' => 'diagnostics',
        'header_cta_primary' => 'Contact Us',
        'floating_whatsapp_label' => 'Contact us on WhatsApp',
        'brand_alt' => 'Back2Value logo',
        'breadcrumb_home' => 'Home',
        'footer_items' => [
            ['label' => 'Batteries', 'target' => 'products'],
            ['label' => 'Services', 'target' => 'services'],
            ['label' => 'Regeneration', 'target' => 'regeneration'],
            ['label' => 'Solutions', 'target' => 'solutions'],
            ['label' => 'Sustainability', 'target' => 'sustainability'],
            ['label' => 'About us', 'target' => 'resources'],
            ['label' => 'Diagnostics', 'target' => 'diagnostics'],
        ],
        'footer_whatsapp_label' => 'WhatsApp',
        'footer_copyright' => 'Back2Value shpk. All rights reserved.',
        'footer_partner_line' => 'Official RID-Batterie partner in Albania',
    ],
    'compliance_banner' => [
        'enabled' => true,
        'prefix' => 'Back2Value operates in line with',
        'first_label' => 'Albanian waste-management legislation',
        'first_url' => 'https://akm.gov.al/ova_doc/ligj-nr-10463-date-22-9-2011-per-menaxhimin-e-integruar-te-mbetjeve/',
        'middle' => 'and the',
        'second_label' => 'EU regulatory framework',
        'second_url' => 'https://eur-lex.europa.eu/eli/reg/2023/1542/oj/',
        'suffix' => 'for batteries, waste batteries, and circular economy principles.',
    ],
    'contact_cards' => [
        'whatsapp_label' => 'WhatsApp',
        'email_label' => 'Email',
        'phone_label' => 'Phone',
        'map_label' => 'Open in Maps',
    ],
    'products' => [
        [
            'key' => 'traction',
            'title' => 'Traction Batteries (PzS)',
            'status' => 'In stock',
            'description' => 'The RID PzS series for electric forklifts and warehouse machinery. Heavy-duty cycles, long service life and optimal energy consumption.',
            'features' => [
                'DIN / BS dimensions — fits every forklift brand',
                'High cycle life',
                '2-year warranty direct from the factory',
            ],
            'image' => 'images/battery-pzs.jpg',
            'image_alt' => 'RID traction battery with industrial cells and orange caps',
            'sort_order' => 1,
        ],
        [
            'key' => 'ups-industrial',
            'title' => 'UPS & Industrial Batteries (AGM / OPzV)',
            'status' => 'Pre-order',
            'description' => 'RID Xtreme AGM and OPzV — maintenance-free, for critical power systems, banks, telecoms and data centres.',
            'features' => [
                'Valve-regulated, zero maintenance',
                'Up to 20 years of service life (OPzV)',
                'Suitable for Bank of Albania audits',
            ],
            'image' => 'images/battery-ups.jpg',
            'image_alt' => 'Green RID batteries for UPS systems and industrial use',
            'sort_order' => 2,
        ],
        [
            'key' => 'starting',
            'title' => 'Starting Batteries (Fleet & Trucks)',
            'status' => 'In stock',
            'description' => 'The RID ST2 series for trucks, buses, construction machinery and commercial fleets. High starting power (CCA), even in extreme temperatures.',
            'features' => [
                'High CCA — reliable starting',
                'Exchange against an old battery (core exchange)',
                '2-year warranty',
            ],
            'image' => 'images/battery-start.jpg',
            'image_alt' => 'RID-Batterie starting battery for cars and trucks',
            'sort_order' => 3,
        ],
    ],
    'services' => [
        [
            'key' => 'diagnostics',
            'title' => 'Professional Diagnostics',
            'description' => 'Real capacity health testing (State of Health) with RID-Logger equipment. Find out the condition of the battery before a failure occurs.',
            'icon' => 'clipboard',
            'sort_order' => 1,
        ],
        [
            'key' => 'reconditioning',
            'title' => 'Regeneration & Capacity Restoration',
            'description' => 'With the RID Tester the battery is inspected, tested and diagnosed, then regenerated (service: battery regeneration). This service is offered free of charge within 3 years for every new battery bought from Back2Value shpk. Through a buyer database, customers are contacted 1 year after purchase to check the condition of the battery, and recharging is offered if the customer wishes to optimise the battery life.',
            'icon' => 'refresh',
            'sort_order' => 2,
        ],
        [
            'key' => 'maintenance',
            'title' => 'Maintenance Contracts (SLA)',
            'description' => 'Periodic inspections, official technical reports for audits and emergency response within 48 hours. Fully compliant documentation.',
            'icon' => 'calendar',
            'sort_order' => 3,
        ],
        [
            'key' => 'delivery',
            'title' => 'Collection & Delivery',
            'description' => 'We collect and return batteries anywhere in Albania. A complete logistics service that saves you time and downtime.',
            'icon' => 'download',
            'sort_order' => 4,
        ],
    ],
    'about' => [
        'eyebrow' => 'OUR ADVANTAGE',
        'title' => 'Why Back2Value?',
        'description' => 'We are the only ones combining original German batteries with local technical expertise — in Albania.',
        'points' => [
            [
                'key' => 'exclusive-importer',
                'title' => 'Exclusive German Importer',
                'icon' => 'shield',
                'description' => 'Back2Value shpk is the only authorised partner of RID-Batterie Germany in Albania. Every product carries a direct factory warranty — no copies, no grey-market substitutes.',
                'label' => 'RID-Batterie GmbH, Germany',
            ],
            [
                'key' => 'local-service',
                'title' => 'Professional Local Maintenance',
                'icon' => 'refresh',
                'description' => 'We provide the only technical service structured for industrial batteries in Albania. RID-Logger diagnostics, professional regeneration and SLA contracts with official documentation — all from our base in Pogradec.',
                'label' => '',
            ],
        ],
        'faqs' => [
            [
                'question' => 'Is Back2Value an authorised RID-Batterie partner?',
                'answer' => 'Yes. Back2Value shpk is the only authorised partner of RID-Batterie Germany in Albania.',
            ],
            [
                'question' => 'Where is your technical team based?',
                'answer' => 'Our technical base is in Pogradec. We provide services to customers throughout Albania.',
            ],
            [
                'question' => 'What types of batteries do you support?',
                'answer' => 'We supply and maintain industrial batteries for forklifts, UPS systems and vehicle fleets.',
            ],
            [
                'question' => 'Do you offer battery diagnostics and regeneration?',
                'answer' => 'Yes. We assess battery condition with RID-Logger equipment and provide professional regeneration, maintenance and technical documentation.',
            ],
        ],
    ],
    'stats' => [
        'items' => [
            ['key' => 'warranty', 'value' => '2yr', 'label' => 'Product Warranty', 'sort_order' => 1],
            ['key' => 'lifespan', 'value' => '20yr', 'label' => 'OPzV Service Life', 'sort_order' => 2],
            ['key' => 'response', 'value' => '48h', 'label' => 'Emergency SLA', 'sort_order' => 3],
            ['key' => 'rank', 'value' => '#1', 'label' => 'Exclusive Importer', 'sort_order' => 4],
        ],
    ],
    'trust' => [
        'items' => [
            ['key' => 'exclusive', 'text' => 'Exclusive Importer in Albania', 'icon' => 'shield'],
            ['key' => 'german', 'text' => 'German Manufacturing', 'icon' => 'factory'],
            ['key' => 'warranty', 'text' => '2-Year Warranty', 'icon' => 'calendar'],
            ['key' => 'service', 'text' => 'Technical Service · Pogradec', 'icon' => 'services'],
        ],
    ],
    'value_props' => [
        'eyebrow' => 'EXTENDING BATTERY LIFE',
        'title' => 'We restore 50–100% of the original capacity',
        'description' => 'We diagnose, recharge and regenerate your industrial batteries before they are replaced. The result: more life cycles, lower operating costs and a far smaller environmental impact.',
        'items' => [
            [
                'key' => 'life-extension',
                'icon' => 'battery',
                'value' => '50–100%',
                'title' => 'Capacity restored',
                'description' => 'With RID-Logger we measure the real condition (State of Health), then the regeneration process restores 50–100% of the original capacity and adds new working cycles.',
            ],
            [
                'key' => 'cost-reduction',
                'icon' => 'coins',
                'value' => '−60%',
                'title' => 'Cost reduction',
                'description' => 'Reactivation and periodic maintenance cost far less than buying new batteries, without compromising the reliability of critical systems.',
            ],
            [
                'key' => 'responsible-management',
                'icon' => 'leaf',
                'value' => '100%',
                'title' => 'Responsible management',
                'description' => 'We collect used batteries, hand them over for licensed recycling and document every step of the process in line with environmental requirements.',
            ],
        ],
    ],
    'diagnostics_teaser' => [
        'eyebrow' => 'QUICK DIAGNOSTICS',
        'title' => 'Book a test for your batteries',
        'description' => 'Send a quick request and our technical team will schedule the test, regeneration or collection of your batteries within 24 hours.',
        'steps' => [
            [
                'key' => 'request',
                'title' => 'Request',
                'description' => 'Fill in the online form or message us on WhatsApp with the number, type and location of the batteries.',
            ],
            [
                'key' => 'assessment',
                'title' => 'Assessment',
                'description' => 'We test capacity and internal resistance with RID-Logger equipment and determine whether the battery can be regenerated.',
            ],
            [
                'key' => 'reactivation',
                'title' => 'Capacity restoration',
                'description' => 'We apply the regeneration and recharge process, test again and hand over the official technical report.',
            ],
        ],
        'cta' => 'Book a Diagnostic',
        'cta_target' => 'diagnostics',
        'secondary_cta' => 'View the services',
        'secondary_cta_target' => 'services',
    ],
    'circular_process' => [
        'eyebrow' => 'OUR PROCESS',
        'title' => 'From collection to recirculation',
        'description' => 'Every battery passes through the same controlled cycle: collection, testing, sorting and activation — through to resale or recycling.',
        'steps' => [
            [
                'key' => 'collection',
                'icon' => 'truck',
                'title' => 'Collection',
                'description' => 'We collect used batteries from businesses, car workshops and individuals throughout Albania.',
            ],
            [
                'key' => 'testing',
                'icon' => 'pulse',
                'title' => 'Testing',
                'description' => 'Every battery is tested with the RID Tester: real capacity, internal resistance and state of charge are measured.',
            ],
            [
                'key' => 'sorting',
                'icon' => 'layers',
                'title' => 'Sorting',
                'description' => 'Batteries are separated by condition: returnable to service, for second-life use, or for recycling.',
            ],
            [
                'key' => 'activation',
                'icon' => 'zap',
                'title' => 'Activation',
                'description' => 'Suitable batteries are regenerated with the RID Rigenerator and returned to circulation with verified performance.',
            ],
        ],
        'note_eyebrow' => 'CIRCULAR ECONOMY',
        'note_title' => 'Zero landfill waste',
        'note_description' => 'Every step is documented — from collection to final destination, in compliance with Albanian and European battery legislation.',
        'note_cta' => 'Learn about sustainability',
        'note_cta_target' => 'sustainability',
        'outcomes' => [
            [
                'key' => 'resale',
                'icon' => 'coins',
                'title' => 'Resale',
                'description' => 'Regenerated batteries return to the market with a warranty and a technical report.',
            ],
            [
                'key' => 'recycling',
                'icon' => 'recycle',
                'title' => 'Recycling',
                'description' => 'What cannot be returned to service is sent for licensed recycling.',
            ],
        ],
    ],
    'partners' => [
        'eyebrow' => 'PARTNERS & CERTIFICATIONS',
        'title' => 'Supported by international partners',
        'description' => 'We work with German manufacturers and European programmes that guarantee technical standards, transparency and environmental responsibility.',
        'items' => [
            [
                'key' => 'rid-batterie',
                'name' => 'RID Batterie',
                'country' => 'Germany',
                'description' => 'German manufacturer and long-term production partner for industrial batteries.',
                'logo' => 'images/partners/rid-batterie.svg',
                'logo_alt' => 'RID Batterie logo',
                'logo_background' => 'transparent',
            ],
            [
                'key' => 'enterprise-europe-network',
                'name' => 'Enterprise Europe Network',
                'country' => 'EU',
                'description' => 'European business support network for innovation, partnerships and market expansion.',
                'logo' => 'images/partners/enterprise-europe-network.svg',
                'logo_alt' => 'Enterprise Europe Network logo',
                'logo_background' => 'transparent',
            ],
            [
                'key' => 'europe-albania',
                'name' => 'European Union in Albania',
                'country' => 'Albania · EU',
                'description' => 'European cooperation programmes supporting sustainable business development.',
                'logo' => 'images/partners/europe-albania.svg',
                'logo_alt' => 'European Union in Albania logo',
                'logo_background' => 'transparent',
            ],
            [
                'key' => 'nehemiah-gateway',
                'name' => 'Nehemiah Gateway Albania',
                'country' => 'Albania',
                'description' => 'Partner organisation for sustainable development, technical training and local social projects.',
                'logo' => 'images/partners/nehemiah-gateway.svg',
                'logo_alt' => 'Nehemiah Gateway Albania logo',
                'logo_background' => 'transparent',
            ],
            [
                'key' => 'auto-servis-jazxhi',
                'name' => 'Auto Servis Jazxhi',
                'country' => 'Albania',
                'description' => 'Workshop and vehicle service partner for local fleet support.',
                'logo' => 'images/partners/auto-servis-jazxhi.svg',
                'logo_alt' => 'Auto Servis Jazxhi logo',
                'logo_background' => 'transparent',
            ],
            [
                'key' => 'auto-sulo-son',
                'name' => 'Auto Sulo & Son',
                'country' => 'Albania',
                'description' => 'Automotive service and parts partner for the local market.',
                'logo' => 'images/partners/auto-sulo-son.svg',
                'logo_alt' => 'Auto Sulo and Son logo',
                'logo_background' => 'transparent',
            ],
        ],
    ],
    'application_filters' => [
        'industrial' => [
            'label' => 'Industrial & Forklift',
            'categories' => [
                'RID Motive Power (Forklifts)',
                'Hoppecke Series FNC (NiCd)',
                'Hoppecke Series GroE',
                'Hoppecke Series OGi',
            ],
        ],
        'backup_power' => [
            'label' => 'Backup Power & UPS',
            'application_types' => ['backup_power'],
        ],
        'solar' => [
            'label' => 'Solar & Renewable Energy',
            'application_types' => ['solar'],
        ],
        'auto' => [
            'label' => 'Auto & Vehicles',
            'categories' => ['RID ST Series (Commercial Vehicles)'],
        ],
    ],
    'services_page' => [
        'meta_title' => 'Technical Services | Back2Value',
        'meta_description' => 'Diagnostics, regeneration, SLA maintenance contracts and industrial battery collection in Albania. Book a diagnostic or request a service contract.',
        'eyebrow' => 'OUR SERVICES',
        'title' => 'Complete solutions for battery lifetime',
        'description' => 'From the first diagnostic to the collection of used batteries — we cover the entire lifecycle of your industrial batteries.',
        'hero_cta_primary' => 'Book a Diagnostic',
        'hero_cta_primary_target' => 'diagnostics',
        'hero_cta_secondary' => 'View products',
        'hero_cta_secondary_target' => 'products',
        'detail_link' => 'RID Tester & RID Rigenerator',
        'detail_link_target' => 'regeneration',
        'items' => [
            [
                'key' => 'diagnostics',
                'icon' => 'clipboard',
                'title' => 'Battery Diagnostics & Assessment',
                'description' => 'We measure real capacity, internal resistance and voltage with RID-Logger equipment, then compile an official technical report on the condition of your batteries (State of Health).',
                'features' => [
                    'Full bank testing, cell by cell',
                    'Official technical report for auditing and decision-making',
                    'Regeneration cost assessment versus replacement',
                    'Written recommendation for the next maintenance cycle',
                ],
            ],
            [
                'key' => 'reactivation',
                'icon' => 'refresh',
                'title' => 'Battery Recharge & Regeneration',
                'description' => 'We apply controlled charging and desulfation pulses to restore lost capacity. This service is offered free of charge within 3 years for new batteries bought from Back2Value shpk.',
                'features' => [
                    'Restoration of 50–100% of the original capacity',
                    'Desulfation pulses and cell balancing',
                    'Free initial recharge within 3 years of purchase',
                    'Final test and report of the restored capacity',
                ],
            ],
            [
                'key' => 'maintenance',
                'icon' => 'calendar',
                'title' => 'Maintenance Contracts (SLA)',
                'description' => 'Periodic inspections, technical reports for audits and emergency response within 48 hours — with a schedule planned according to the criticality of your systems.',
                'features' => [
                    'Periodic inspection calendar per the SLA',
                    'Official reporting for Bank of Albania requirements',
                    'Emergency response within 48 hours',
                    'Management of the battery inventory and test history',
                ],
            ],
            [
                'key' => 'trade-in',
                'icon' => 'download',
                'title' => 'Battery Collection & Trade-In',
                'description' => 'We collect used batteries throughout Albania, transport them for licensed recycling and offer a trade-in value for new batteries.',
                'features' => [
                    'Collection and transport of used batteries',
                    'Licensed recycling with full documentation',
                    'Trade-in value deductible from the purchase of new batteries',
                    'Service tailored to car workshops and fleets',
                ],
            ],
        ],
        'maintenance_eyebrow' => 'MAINTENANCE CONTRACTS',
        'maintenance_title' => 'Request an SLA contract for your fleet',
        'maintenance_description' => 'Fill in the details below and our sales team will prepare the technical and commercial proposal for your organisation.',
        'form_company_label' => 'Company name',
        'form_contact_label' => 'Contact person',
        'form_email_label' => 'Email',
        'form_phone_label' => 'Phone',
        'form_sector_label' => 'Sector',
        'form_sectors' => [
            'telecom' => 'Telecommunications',
            'data_center' => 'Data Centre',
            'banks' => 'Banks & Financial Institutions',
        ],
        'form_fleet_label' => 'Number of batteries in the fleet',
        'form_fleet_default' => '50',
        'form_requirements_label' => 'Technical requirements',
        'form_requirements_hint' => 'Describe the locations, the battery type and the desired frequency of inspections.',
        'form_message_label' => 'Additional notes (optional)',
        'form_submit' => 'Send the request',
        'form_hint' => 'We reply within 24 business hours.',
        'cta_title' => 'Not sure whether your batteries can be regenerated?',
        'cta_description' => 'Send a diagnostic request and we will make the technical decision based on real capacity and internal resistance measurements.',
        'cta_primary' => 'Book a Diagnostic',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'View the products',
        'cta_secondary_target' => 'products',
    ],
    'calculator' => [
        'eyebrow' => 'QUICK ESTIMATE',
        'title' => 'What is regeneration worth to your battery bank?',
        'description' => 'Enter the number of batteries and their average weight to estimate the material recovered and the cost saving versus replacement.',
        'count_label' => 'Number of batteries',
        'weight_label' => 'Average weight of one battery (kg)',
        'count_default' => 24,
        'weight_default' => 32,
        'capacity_value' => '50–100%',
        'capacity_label' => 'Capacity restored through regeneration',
        'cost_value' => '−55%',
        'cost_label' => 'Cost versus replacement with new batteries',
        'lead_label' => 'Lead recovered for licensed recycling',
        'lead_unit' => 'kg',
        'co2_label' => 'CO₂ avoided by not producing new batteries',
        'co2_unit' => 'kg',
        'note' => 'The estimate is based on our technical experience: 50–100% capacity restoration, an average 55% cost reduction versus replacement, a lead content of about 55% of the weight and an avoidance of about 1.6 kg CO₂ per kilogram of lead recovered. Figures are indicative — the real result is determined after the technical diagnostic.',
        'primary_label' => 'Book a Diagnostic',
        'primary_target' => 'diagnostics',
        'secondary_label' => 'See the environmental impact',
        'secondary_target' => 'sustainability',
        'lead_share_percent' => 55,
        'co2_per_kg' => 2,
    ],
    'regeneration_page' => [
        'meta_title' => 'RID Tester & RID Rigenerator | Back2Value',
        'meta_description' => 'Professional testing, diagnostics and regeneration of batteries with RID Tester and RID Rigenerator equipment. Free within 3 years for every new battery.',
        'eyebrow' => 'TECHNICAL SERVICES',
        'title' => 'RID Tester & RID Rigenerator',
        'description' => 'Testing, diagnostics and regeneration of batteries as a professional service for Back2Value customers — not as products for sale.',
        'hero_cta_primary' => 'Book a Diagnostic',
        'hero_cta_secondary' => 'View the services',
        'hero_cta_secondary_target' => 'services',
        'teaser_eyebrow' => 'BATTERY REGENERATION',
        'teaser_title' => 'RID Tester & RID Rigenerator',
        'teaser_description' => 'Two pieces of professional equipment underpin our regeneration service: the RID Tester inspects, tests and diagnoses every battery, while the RID Rigenerator restores lost capacity. Both are offered as a service to customers, not as products for sale.',
        'teaser_cta' => 'Learn more',
        'teaser_cta_target' => 'regeneration',
        'teaser_secondary_cta' => 'Book a Diagnostic',
        'teaser_secondary_cta_target' => 'diagnostics',
        'tools_eyebrow' => 'OUR TWO PIECES OF EQUIPMENT',
        'tools_title' => 'The equipment we use every day',
        'tools_description' => 'Both devices are part of our technical service base in Pogradec and are used for every battery entrusted to us.',
        'tools' => [
            [
                'key' => 'rid-tester',
                'icon' => 'battery',
                'model' => 'RID BMG-30 Battery Tester',
                'title' => 'RID Tester',
                'description' => 'With the RID Tester the battery is inspected, tested and diagnosed: real capacity, internal resistance and state of charge are measured, to establish whether the battery can be regenerated.',
                'features' => [
                    'Capacity and internal resistance measurement',
                    'Diagnostics of the real condition of the battery (State of Health)',
                    'Determines whether the battery qualifies for regeneration',
                    'Technical report that backs up every decision',
                ],
            ],
            [
                'key' => 'rid-rigenerator',
                'icon' => 'recycle',
                'model' => 'RID BRG Series Battery Regenerator',
                'title' => 'RID Rigenerator',
                'description' => 'The RID Rigenerator applies the professional regeneration process with controlled charging and desulfation pulses, restoring up to 50–100% of the original capacity without replacing the battery bank.',
                'features' => [
                    'Restoration of 50–100% of the original capacity',
                    'Controlled charging and desulfation pulses',
                    'Second test after the process with an official report',
                    'Offered as a service — not as a product for sale',
                ],
            ],
        ],
        'lab_eyebrow' => 'BATTERY LABORATORY',
        'lab_title' => 'From intake to performance test',
        'lab_description' => 'Every battery entrusted to us goes through the same documented process — whether it is a single battery or an entire bank.',
        'lab_panel_title' => 'How our battery laboratory works:',
        'lab_brand_logo' => 'images/rid-lab/rid-wordmark.png',
        'lab_brand_alt' => 'RID Battery · Germany',
        'lab_steps' => [
            [
                'key' => 'pranimi',
                'title' => 'Intake',
                'description' => 'Bring us the battery and rely on our complete service.',
                'image' => 'images/rid-lab/step-1.png',
                'alt' => 'Delivering a battery at the Back2Value laboratory',
                'width' => 440,
                'height' => 280,
            ],
            [
                'key' => 'diagnostikimi',
                'title' => 'Battery diagnostics',
                'description' => 'We analyse the current condition and assess whether regeneration makes technical and economic sense.',
                'image' => 'images/rid-lab/step-2.png',
                'alt' => 'Battery diagnostics with the RID Tester',
                'width' => 440,
                'height' => 334,
            ],
            [
                'key' => 'rigjenerimi',
                'title' => 'Regeneration',
                'description' => 'Suitable batteries are treated in a targeted way and reactivated.',
                'image' => 'images/rid-lab/step-3.png',
                'alt' => 'Battery regeneration with the RID Rigenerator',
                'width' => 440,
                'height' => 365,
            ],
            [
                'key' => 'testi-performances',
                'title' => 'Performance test',
                'description' => 'Final tests confirm power, stability and readiness for use.',
                'image' => 'images/rid-lab/step-4.png',
                'alt' => 'Final performance test of the regenerated battery',
                'width' => 440,
                'height' => 316,
            ],
        ],
        'lab_note' => 'Get a tested, fully functional battery along with a detailed assessment: predicted remaining service life and the success rate of the regeneration.',
        'lab_badge_image' => 'images/rid-lab/badge-quality.png',
        'lab_badge_alt' => 'Quality seal — battery inspected by Back2Value',
        'lab_badge_width' => 380,
        'lab_badge_height' => 343,
        'process_eyebrow' => 'HOW IT WORKS',
        'process_title' => 'From purchase to regeneration',
        'process_description' => 'Every new battery bought from Back2Value shpk enters a documented cycle of inspection and regeneration.',
        'process_steps' => [
            [
                'key' => 'purchase',
                'title' => 'Purchase and registration',
                'description' => 'Every new battery bought from Back2Value shpk is registered in the buyer database.',
            ],
            [
                'key' => 'testing',
                'title' => 'Inspection with the RID Tester',
                'description' => 'One year after the purchase, our team contacts you to check the condition of the battery and test its capacity and resistance with the RID Tester.',
            ],
            [
                'key' => 'reconditioning',
                'title' => 'Regeneration with the RID Rigenerator',
                'description' => 'If the battery qualifies, controlled recharging and regeneration are provided to optimise its life — with an official technical report.',
            ],
        ],
        'offer_eyebrow' => 'OFFER FOR CUSTOMERS',
        'offer_title' => 'Free within 3 years for every new battery',
        'offer_description' => 'This service is offered free of charge within 3 years for every new battery bought from Back2Value shpk. Through a database, customers are contacted 1 year after the purchase to check the condition of the battery, and recharging is offered if you wish to optimise its life.',
        'cta_title' => 'Would you like to see regeneration in action?',
        'cta_description' => 'Bring the battery to our laboratory in Pogradec and our technical team will diagnose it, regenerate it and give you the official report.',
        'cta_primary' => 'Book a Diagnostic',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'View the services',
        'cta_secondary_target' => 'services',
    ],
    'solutions' => [
        'meta_title' => 'Sector solutions | Back2Value',
        'meta_description' => 'Battery solutions for industry, renewable energy, automotive and the public sector: SLA contracts, technical reporting, regeneration and collection in Albania.',
        'eyebrow' => 'SECTOR SOLUTIONS',
        'title' => 'Who we work with',
        'description' => 'The same technical services, adapted to how you operate, your budget and your documentation requirements.',
        'hero_cta_primary' => 'Book a Diagnostic',
        'hero_cta_secondary' => 'View the services',
        'hero_cta_secondary_target' => 'services',
        'items' => [
            [
                'key' => 'enterprise',
                'icon' => 'factory',
                'title' => 'Enterprise & Industry',
                'audience' => 'Telecommunications, banking, data centres, construction, agribusiness and logistics',
                'description' => 'Operations with critical systems that cannot tolerate downtime. Maintenance projects and fast response prevent unexpected battery failures.',
                'benefits' => [
                    'SLA contracts with emergency response within 48 hours',
                    'Official reporting for Bank of Albania audits',
                    'Complete management of the battery inventory by location',
                    'Reduced operating costs for backup power',
                ],
                'applications' => ['industrial', 'backup_power'],
            ],
            [
                'key' => 'renewable',
                'icon' => 'sun',
                'title' => 'Renewable Energy',
                'audience' => 'Solar system operators, off-grid projects and backup power users',
                'description' => 'Solar system batteries lose capacity before the end of their life. Testing and regeneration restore energy output for a far smaller investment.',
                'benefits' => [
                    'Assessment of the real capacity of the battery bank',
                    'Cell balancing and restoration of lost capacity',
                    'Technical advice on system sizing',
                    'Maintenance planning by season',
                ],
                'applications' => ['solar'],
            ],
            [
                'key' => 'automotive',
                'icon' => 'car',
                'title' => 'Automotive & Consumer',
                'audience' => 'Vehicle owners, car workshops, families and home solar system users',
                'description' => 'Fast service for vehicle and home system batteries, with collection and a trade-in value for used batteries.',
                'benefits' => [
                    'Fast testing and a clear diagnosis',
                    'Trade-in value for old batteries',
                    'Recharge and regeneration where technically possible',
                    'Accessible collection points in the main cities',
                ],
                'applications' => ['auto', 'solar'],
            ],
            [
                'key' => 'public-sector',
                'icon' => 'landmark',
                'title' => 'Public Sector',
                'audience' => 'Municipalities, hospitals, schools, institutions and public enterprises',
                'description' => 'Full documentation, transparent procurement procedures and planned maintenance for institutions that manage critical infrastructure.',
                'benefits' => [
                    'Technical reports suitable for public procurement',
                    'Maintenance calendar with controllable deadlines',
                    'End-of-life battery management plan',
                    'Training of technical staff for basic checks',
                ],
                'applications' => ['backup_power', 'industrial'],
            ],
        ],
        'process_eyebrow' => 'HOW WE WORK',
        'process_title' => 'From technical assessment to report',
        'process_description' => 'Every engagement follows the same steps: measurement, data-driven technical decision, execution and documentation.',
        'process_steps' => [
            ['title' => 'Inventory & criticality', 'description' => 'We record the model, capacity, installation date, location and criticality of each battery bank.'],
            ['title' => 'Measurement & decision', 'description' => 'We test capacity and internal resistance, then compare regeneration with replacement.'],
            ['title' => 'Execution & report', 'description' => 'We apply the chosen service, test again and deliver the official technical report for auditing.'],
        ],
        'cta_title' => 'Find the solution for your sector',
        'cta_description' => 'From forklift fleets to data centre battery banks — we tailor the service, schedule and documentation to your requirements.',
        'cta_primary' => 'Book a Diagnostic',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'Product catalogue',
        'cta_secondary_target' => 'products',
    ],
    'sustainability' => [
        'meta_title' => 'Sustainability & compliance | Back2Value',
        'meta_description' => 'Battery life extension, licensed recycling and documentation for audits: how we responsibly manage every battery bank in Albania.',
        'eyebrow' => 'SUSTAINABILITY & COMPLIANCE',
        'title' => 'Responsible battery management',
        'description' => 'Extending battery life is the simplest environmental action available: less lead extracted, fewer batteries discarded and less energy spent on new production.',
        'hero_cta_primary' => 'Book a Diagnostic',
        'hero_cta_secondary' => 'View the services',
        'hero_cta_secondary_target' => 'services',
        'commitments_eyebrow' => 'OUR COMMITMENTS',
        'commitments_title' => 'Four operating commitments',
        'commitments_description' => 'We apply the same standards for every customer — from a single battery to full institutional fleets.',
        'commitments' => [
            [
                'key' => 'life-extension-first',
                'icon' => 'battery',
                'title' => 'Life extension before replacement',
                'description' => 'We always assess whether a battery can be regenerated before we suggest you buy a new one.',
            ],
            [
                'key' => 'licensed-recycling',
                'icon' => 'recycle',
                'title' => 'Licensed recycling',
                'description' => 'End-of-life batteries are collected and handed over only to licensed recycling plants, with full traceability.',
            ],
            [
                'key' => 'documentation',
                'icon' => 'document',
                'title' => 'Full documentation',
                'description' => 'Every collection, test and treatment is documented, so the entity can meet environmental and financial audit requirements.',
            ],
            [
                'key' => 'customer-education',
                'icon' => 'academic',
                'title' => 'Customer education',
                'description' => 'We train customer staff on charging, operating temperature, ventilation and basic maintenance to extend battery life.',
            ],
        ],
        'metrics' => [
            ['key' => 'capacity-restored', 'value' => '50–100%', 'label' => 'Capacity restored'],
            ['key' => 'cost-saved', 'value' => '−60%', 'label' => 'Cost versus replacement'],
            ['key' => 'lead-recovered', 'value' => '98%', 'label' => 'Recoverable lead'],
            ['key' => 'response', 'value' => '48h', 'label' => 'Emergency SLA response'],
        ],
        'compliance_eyebrow' => 'DOCUMENTATION',
        'compliance_title' => 'Compliance & documentation',
        'compliance_description' => 'We support entities that must prove battery maintenance and treatment to auditors and supervisory institutions.',
        'compliance_points' => [
            'Technical reports for battery maintenance in UPS and backup power systems',
            'Maintenance documentation as required by financial supervision (Decision No. 48/2024)',
            'Certificates of collection and handover for licensed recycling',
            'Register of tests, maintenance and history for each battery bank',
        ],
        'cta_title' => 'Return your batteries to the cycle, not to waste',
        'cta_description' => 'We assess the real capacity of your batteries and show you clearly when regeneration is the right choice.',
        'cta_primary' => 'Book a Diagnostic',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'Resource centre',
        'cta_secondary_target' => 'resources',
    ],
    'resources' => [
        'meta_title' => 'Resource centre | Back2Value',
        'meta_description' => 'Practical guides on industrial battery lifetime: charging, maintenance, cost, recycling and preparing documentation for audits.',
        'eyebrow' => 'CUSTOMER EDUCATION',
        'title' => 'Resource centre',
        'description' => 'Practical guides on extending battery life and the economic and environmental benefits.',
        'hero_cta_primary' => 'Book a Diagnostic',
        'hero_cta_secondary' => 'Technical services',
        'hero_cta_secondary_target' => 'services',
        'article_more_label' => 'Read the full guide',
        'articles' => [
            [
                'key' => 'extend-battery-life',
                'category' => 'Battery lifetime',
                'title' => 'How to extend the life of your industrial batteries',
                'excerpt' => 'Temperature, depth of discharge and periodic maintenance determine battery life more than any other factor.',
                'reading_time' => '4 min',
                'paragraphs' => [
                    'Operating temperature is the number one factor: above 25°C, every 10°C increase noticeably shortens the expected life of lead-acid batteries.',
                    'Depth of discharge directly affects the number of cycles. Limiting the discharge and recharging in time increases the total cycles a battery can deliver.',
                    'Periodic voltage and internal resistance checks reveal weak cells before they damage the entire battery bank.',
                ],
            ],
            [
                'key' => 'reactivation-vs-replacement',
                'category' => 'Economics',
                'title' => 'Regenerate or replace? How to make the right decision',
                'excerpt' => 'Not every battery needs replacing. The criterion is the remaining capacity and the operating conditions, not the age of the battery.',
                'reading_time' => '5 min',
                'paragraphs' => [
                    'When the measured capacity remains above half the expected capacity, the battery usually qualifies for regeneration and controlled recharging.',
                    'The assessment must include physical access, ambient conditions and the criticality of the system. For old, unsupervised battery banks, planned replacement is safer.',
                    'The right comparison is not just the purchase cost: factor in the energy used for recharging, capacity losses and downtime.',
                ],
            ],
            [
                'key' => 'environmental-impact',
                'category' => 'Sustainability',
                'title' => 'The environmental impact of batteries: what regeneration changes',
                'excerpt' => 'Recycling is essential, but extending battery life is the step that prevents waste from being created at source.',
                'reading_time' => '4 min',
                'paragraphs' => [
                    'Producing a new battery requires lead extraction and processing, considerable energy and international transport. Life extension avoids these environmental costs for every additional year of service.',
                    'Regeneration reduces the volume of batteries entering the waste stream and delays the purchase of new products.',
                    'Batteries that finally leave our service are handed over for licensed recycling, where the lead is recovered almost completely and returned to production.',
                ],
            ],
            [
                'key' => 'ups-battery-audit',
                'category' => 'Compliance',
                'title' => 'UPS battery checks for financial audits',
                'excerpt' => 'Financial institutions must document the maintenance of UPS system batteries. Here is how to prepare the file.',
                'reading_time' => '6 min',
                'paragraphs' => [
                    'Auditors require proof that backup power systems are maintained continuously and that batteries are replaced according to plan.',
                    'The file must contain the battery inventory with installation dates, capacity test reports, the maintenance history and replacement recommendations.',
                    'Maintenance contracts with periodic reporting give the institution full traceability without committing internal resources.',
                ],
            ],
            [
                'key' => 'charging-best-practices',
                'category' => 'Operation',
                'title' => 'Correct charging: the mistakes that shorten battery life',
                'excerpt' => 'Overcharging, sulfation and unbalanced cells are the main causes of capacity loss.',
                'reading_time' => '5 min',
                'paragraphs' => [
                    'Chargers with temperature compensation and phased charging prevent overcharging, which causes electrolyte loss and oxidation of the positive plates.',
                    'Lead sulfation is reversible in its early stages: desulfation pulses and controlled charge cycles restore a good part of the lost capacity.',
                    'Unbalanced cells discharge the bank unevenly. Periodic measurement and cell balancing preserve the performance of the whole system.',
                ],
            ],
            [
                'key' => 'maintenance-plan',
                'category' => 'Maintenance',
                'title' => 'How to build an annual battery maintenance plan',
                'excerpt' => 'A simple inspection calendar prevents unplanned costs and system downtime.',
                'reading_time' => '5 min',
                'paragraphs' => [
                    'Start with a complete inventory: model, capacity, installation date, location and criticality of each battery bank.',
                    'Set the inspection frequency according to criticality: critical systems require quarterly checks, secondary ones are fine with an annual check.',
                    'Include the capacity test, internal resistance measurement, terminal cleaning and verification of the charging system in the plan.',
                ],
            ],
        ],
        'planning_eyebrow' => 'PLANNING',
        'planning_title' => 'What to prepare before contacting us',
        'planning_description' => 'The more accurate the inventory, the faster and more precise the assessment we can give you.',
        'planning_points' => [
            'Battery list: brand, model, capacity (Ah), voltage and purchase date',
            'Location of each battery bank and access for inspection',
            'Photos of the battery labels and terminals',
            'Number of batteries you replaced during the last year',
        ],
        'cta_title' => 'Ready to get started?',
        'cta_description' => 'Send your diagnostic request and you will receive an initial technical assessment with no commitment.',
        'cta_primary' => 'Book a Diagnostic',
        'cta_primary_target' => 'diagnostics',
        'cta_secondary' => 'View the services',
        'cta_secondary_target' => 'services',
    ],
    'drop_off_points' => [
        'eyebrow' => 'COLLECTION NETWORK',
        'title' => 'Authorised drop-off and service points',
        'description' => 'We accept batteries for testing, regeneration and recycling at the points below. For fleets and large battery banks we arrange dedicated transport.',
        'items' => [
            [
                'key' => 'pogradec-hq',
                'title' => 'Pogradec — Main Technical Centre',
                'type' => 'Laboratory & authorised service',
                'category' => 'licensed',
                'address' => 'Rruga Nehemia, Buçimas, Pogradec',
                'phone' => '+355 69 273 4476',
                'hours' => 'Monday – Friday · 08:00 – 17:00',
            ],
            [
                'key' => 'tirana-hub',
                'title' => 'Tirana — Service Centre',
                'type' => 'Authorised drop-off point',
                'category' => 'licensed',
                'address' => 'Tirana (address confirmed after the request)',
                'phone' => '+355 69 273 4476',
                'hours' => 'Monday – Saturday · 08:30 – 18:00',
            ],
            [
                'key' => 'durres-point',
                'title' => 'Durrës — Collection Point',
                'type' => 'Battery collection centre',
                'category' => 'collection',
                'address' => 'Durrës (address confirmed after the request)',
                'phone' => '+355 69 273 4476',
                'hours' => 'Monday – Friday · 09:00 – 17:30',
            ],
            [
                'key' => 'workshop-network',
                'title' => 'Partner Car Workshop Network',
                'type' => 'Partner vehicle service',
                'category' => 'workshop',
                'address' => 'Tirana, Durrës, Fier, Shkodër, Elbasan',
                'phone' => '+355 69 273 4476',
                'hours' => 'According to the partner service hours',
            ],
        ],
        'address_label' => 'Address',
        'phone_label' => 'Phone',
        'hours_label' => 'Hours',
    ],
    'diagnostics_page' => [
        'meta_title' => 'Book a battery diagnostic | Back2Value',
        'meta_description' => 'Book a professional diagnostic of your industrial batteries: capacity measurement, official technical report and regeneration assessment.',
        'eyebrow' => 'DIAGNOSTICS & REGENERATION',
        'title' => 'Book a battery diagnostic',
        'description' => 'Fill in the details below and our technical team will confirm the timing, logistics and service terms within 24 hours.',
        'sectors' => [
            'enterprise' => 'Enterprise & Industry',
            'telecom' => 'Telecommunications',
            'banking' => 'Banking & Data Centre',
            'solar' => 'Solar & Renewable Energy',
            'auto' => 'Car Workshop & Fleet',
            'household' => 'Household & Consumer',
            'public_sector' => 'Public Sector',
        ],
        'battery_types' => [
            'rid_industrial' => 'RID-Batterie industrial batteries',
            'ups_backup' => 'UPS / backup power system',
            'solar_storage' => 'Solar system battery',
            'automotive' => 'Vehicle / workshop battery',
            'forklift' => 'Forklift / traction battery',
            'other' => 'Other',
        ],
        'service_preferences' => [
            'pickup' => 'Collection from your location',
            'drop_off' => 'Drop-off at the nearest point',
            'onsite' => 'On-site testing',
            'courier' => 'Transport arranged with a courier',
        ],
        'label_name' => 'Full name',
        'label_company' => 'Company (optional)',
        'label_email' => 'Email',
        'label_phone' => 'Phone',
        'label_sector' => 'Sector',
        'label_battery_type' => 'Battery type',
        'label_date' => 'Preferred date for the test',
        'label_service_preference' => 'Preferred service method',
        'label_notes' => 'Additional notes (optional)',
        'placeholder_select' => 'Select an option',
        'error_summary' => 'The form has errors that need to be corrected:',
        'submit_label' => 'Send the request',
        'submit_hint' => 'We reply within 24 business hours.',
        'success_message' => 'The request was sent successfully. Our technical team will contact you within 24 hours.',
        'cta_title' => 'Before you send the request',
        'cta_description' => 'Gather as much information as possible: the model, capacity and location make our assessment far more accurate.',
        'cta_primary' => 'View the services',
        'cta_primary_target' => 'services',
        'cta_secondary' => 'Educational resources',
        'cta_secondary_target' => 'resources',
    ],
    'catalog_page' => [
        'meta_title' => 'German industrial batteries | Back2Value',
        'meta_description' => 'The RID-Batterie catalogue: OPzS for forklifts, UPS and industry, starting batteries and renewable energy systems. Price on request, delivery in Albania.',
        'badge' => 'Official Portfolio · RID Battery Germany',
        'hero_title' => 'Industrial batteries with clear categories and applications',
        'hero_description' => 'Filter by application or search by model. Every battery comes with a warranty, technical documentation and the option of regeneration after the first cycle.',
        'price_note' => 'Prices are shown on request for B2B orders — contact us for a tailored quote based on quantity and application.',
        'portfolio_label' => 'RID-Batterie GmbH · German Batteries',
        'whatsapp_message' => 'I am interested in batteries from the RID-Batterie catalogue.',
        'search_placeholder' => 'Search by model, brand or category…',
        'search_button' => 'Search',
        'clear_button' => 'Clear',
        'categories_label' => 'Categories',
        'applications_label' => 'Application',
        'all_label' => 'All',
        'model_unit_one' => 'model',
        'model_unit_many' => 'models',
        'finder_title' => 'Find the battery for your vehicle',
        'finder_description' => 'Select the vehicle type and year, and we will show you the RID batteries that match its requirements.',
        'finder_type_label' => 'Vehicle type',
        'finder_type_placeholder' => 'Select the type',
        'finder_make_label' => 'Make',
        'finder_make_placeholder' => 'Select the make',
        'finder_model_label' => 'Model',
        'finder_model_placeholder' => 'Sprinter, Golf, A4…',
        'finder_year_label' => 'Year',
        'finder_fuel_label' => 'Fuel',
        'finder_startstop_label' => 'Start / Stop',
        'finder_capacity_label' => 'Capacity (Ah)',
        'finder_capacity_placeholder' => '74',
        'finder_vin_label' => 'VIN (optional)',
        'finder_vin_placeholder' => 'WVWZZZ1KZAW000001',
        'finder_notes_label' => 'Other details (optional)',
        'finder_notes_placeholder' => 'E.g. I need a 100Ah AGM battery for a van…',
        'finder_submit' => 'Find the match',
        'finder_reset' => 'Clear',
        'finder_hint' => 'Results are based on the starting battery category of the RID fleet. For industrial batteries use the diagnostic request.',
        'category_descriptions' => [
            'RID Motive Power' => 'Traction batteries for electric forklifts and warehouse machinery. DIN/BS dimensions, heavy-duty cycles and a direct factory warranty.',
            'OPzS' => 'Industrial battery banks for critical systems: high capacity, reduced maintenance and service life of up to 20 years.',
            'OPzV' => 'Maintenance-free AGM batteries for UPS, telecoms and data centres. Zero maintenance and stable capacity.',
            'FNC' => 'Professional NiCd series for locomotives, trams and industrial applications with deep discharge cycles.',
            'GroE' => 'Lead series for petrol stations and power grids: deep cycles and reliability in extreme conditions.',
            'OGi' => 'Batteries for construction machinery and similar equipment, with high capacity and resistance to mechanical shock.',
            'RID ST Series' => 'Starting batteries for trucks, buses and construction machinery with high starting power and a 2-year warranty.',
        ],
        'finder_year_placeholder' => 'Select the year',
        'finder_fuel_placeholder' => 'Select the fuel',
        'vehicle_badge' => 'Vehicle search',
        'vin_confirm_label' => 'Confirm the match by VIN',
        'category_fallback_description' => 'Professional solutions for uninterrupted power storage and supply.',
        'empty_title' => 'No battery matched these criteria',
        'empty_description' => 'Try a broader search or send a request for a specific model.',
        'empty_action' => 'Show all batteries',
        'quote_category' => 'Request a quote for this category',
        'quote_whatsapp_message' => 'I would like a quote for the batteries in this category.',
        'contact_title' => 'Contact by email or phone',
        'price_request_label' => 'Price on request',
        'quote_button' => 'Request a Quote',
        'warranty_prefix' => 'Warranty',
        'preorder_notice' => 'All products are sold on pre-order. Contact us for the delivery time and your quote.',
        'stock_label_in_stock' => 'In stock',
        'stock_label_low_stock' => 'Limited stock',
        'stock_label_on_preorder' => 'Pre-order',
        'stock_label_out_of_stock' => 'Out of stock',
        'vin_valid_text' => 'The VIN was found in our catalogue',
        'vin_region_label' => 'Region',
        'vin_year_label' => 'Year',
        'vin_match_text' => 'We recommend',
        'vin_invalid_text' => 'The VIN was not found. Contact us on WhatsApp for a manual check.',
        'recommendation_label' => 'best matching model',
        'bottom_kicker' => 'B2B TECHNICAL CONSULTING',
        'bottom_title' => 'Not sure which model fits?',
        'bottom_description' => 'Send us your requirements list and you will receive a technical proposal with capacity, warranty and delivery time.',
        'bottom_primary' => 'Chat on WhatsApp',
        'bottom_secondary' => 'View the products',
    ],
];
